// 产出 Agent：Codex
const test=require('node:test'),assert=require('node:assert/strict');
const D=require('../src/domain.js'),Seed=require('../src/seed.js'),Store=require('../src/store.js');
const NOW=Date.parse('2026-10-06T08:00:00+08:00');
const customer={id:'C001',role:'customer'},agent={id:'lin',role:'agent'},other={id:'zhou',role:'agent'},manager={id:'manager',role:'manager'},admin={id:'admin',role:'admin'},operator={id:'operator',role:'operator'};
const orderId='EC-SO20261005001',itemId='EC-ITEM-001';
const fresh=()=>Seed.createCommerce(NOW);
const draft=s=>({conversationId:s.conversations[0].id,orderId,itemId,quantity:1,serviceType:'return_refund',reason:'保温杯收到时破损，希望退货退款',evidenceRef:'DEMO-DAMAGE-001'});
function send(s,a,type,data,at=NOW){const r=D.execute(s,a,type,data,at);assert.equal(Store.validCommerce(r.state),true,type+' state must persist');return r;}
function accepted(){let s=fresh(),data=draft(s);const preview=send(s,customer,'previewAftersale',data);data={...data,token:preview.value.token,requestId:'service-cup-request',confirmed:true};const r=send(preview.state,customer,'confirmAftersale',data);return {s:r.state,data,id:r.value,caseId:r.state.commerce.aftersales[0].caseId};}
function approved(){let f=accepted();f.s=send(f.s,agent,'claimConversation',{id:f.s.conversations[0].id}).state;f.s=send(f.s,manager,'submitReview',{aftersaleId:f.id,decision:'approved',reason:'按模拟签收破损规则核定一件129元'}).state;return f;}
function inspected(){const f=approved();f.s=send(f.s,customer,'submitReturn',{aftersaleId:f.id,trackingNumber:'DEMO-RETURN-001'}).state;f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'warehouse_received',version:1}).state;f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'warehouse_passed',version:2}).state;return f;}
function pending(){const f=inspected();f.s=send(f.s,agent,'submitRefund',{aftersaleId:f.id,requestId:'refund-obligation-1'}).state;return f;}
test('preview does not reserve, register or submit; explicit confirmation creates one item application',()=>{const s=fresh(),p=send(s,customer,'previewAftersale',draft(s));assert.equal(p.value.amountCents,12900);assert.equal(p.state.commerce.aftersales.length,0);assert.equal(p.state.commerce.occupancies.length,0);assert.equal(p.state.tickets.length,0);const f=accepted();assert.equal(f.s.commerce.aftersales.length,1);assert.equal(f.s.commerce.occupancies[0].state,'reserved');assert.equal(f.s.cases.find(c=>c.id===f.caseId).status,'open');});
test('same confirmation replays original receipt; changed content with same id is rejected',()=>{const f=accepted(),r=send(f.s,customer,'confirmAftersale',f.data);assert.equal(r.value,f.id);assert.equal(r.state.commerce.occupancies.length,1);assert.throws(()=>D.execute(f.s,customer,'confirmAftersale',{...f.data,reason:'另一个原因'},NOW),/标识|内容/);});
test('changed facts and another request after reservation require recheck, not another application',()=>{let s=fresh(),data=draft(s),p=send(s,customer,'previewAftersale',data);p.state.commerce.items[0].version++;assert.throws(()=>D.execute(p.state,customer,'confirmAftersale',{...data,token:p.value.token,requestId:'stale',confirmed:true},NOW),/变化|核对|预览/);const f=accepted();assert.throws(()=>D.execute(f.s,customer,'previewAftersale',draft(f.s),NOW),/已有|额度|数量/);});
test('ownership, payment facts, quantity and material guard are checked before preview',()=>{const s=fresh();for(const bad of [{itemId:'EC-ITEM-009'},{quantity:2},{evidenceRef:''},{itemId:'EC-ITEM-002'}])assert.throws(()=>D.execute(s,customer,'previewAftersale',{...draft(s),...bad},NOW));s.commerce.payments[0].queryStatus='unknown';assert.throws(()=>D.execute(s,customer,'previewAftersale',draft(s),NOW),/支付|核实|未知/);assert.throws(()=>D.execute(fresh(),agent,'previewAftersale',draft(s),NOW),/无权/);});
test('two named product requests are independently bound and neither exception is completed by lookup',()=>{let s=fresh();s=send(s,customer,'say',{id:s.conversations[0].id,body:'收纳袋没到，保温杯破了想退'},NOW).state;const cases=s.cases.filter(c=>c.service);assert.equal(cases.length,2);assert.deepEqual(new Set(cases.map(c=>c.itemId)),new Set(['EC-ITEM-001','EC-ITEM-002']));assert.ok(cases.every(c=>c.status==='open'&&!c.result));assert.equal(s.commerce.aftersales.length,0);assert.equal(s.conversations[0].state,'queued');assert.equal(D.customerView(s,'C001').services.length,2);});
test('policy question does not trigger a business application; request is only collected until confirmed',()=>{let s=fresh();s=send(s,customer,'say',{id:s.conversations[0].id,body:'保温杯退货规则是什么？'}).state;assert.equal(s.commerce.aftersales.length,0);assert.ok(s.cases.every(c=>!c.service));s=send(s,customer,'say',{id:s.conversations[0].id,body:'保温杯破损，想退货'}).state;assert.equal(s.commerce.aftersales.length,0);assert.equal(s.cases.filter(c=>c.service).length,1);});
test('agent cannot approve or simulate a payment; admin cannot grant business approval',()=>{const f=accepted();for(const [who,cmd,data] of [[agent,'submitReview',{aftersaleId:f.id,decision:'approved',reason:'同意'}],[agent,'applySimulatedReceipt',{aftersaleId:f.id,kind:'refund_succeeded',version:1}],[admin,'submitReview',{aftersaleId:f.id,decision:'approved',reason:'同意'}]])assert.throws(()=>D.execute(f.s,who,cmd,data,NOW),/无权/);});
test('approval and physical receipt are independent from warehouse acceptance and refund',()=>{const f=approved();assert.equal(f.s.commerce.returns[0].status,'awaiting_return');assert.equal(f.s.commerce.refunds.length,0);assert.throws(()=>D.execute(f.s,agent,'submitRefund',{aftersaleId:f.id,requestId:'early'},NOW),/验收|寄回/);f.s=send(f.s,customer,'submitReturn',{aftersaleId:f.id,trackingNumber:'DEMO-RETURN'}).state;f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'warehouse_received',version:1}).state;assert.equal(f.s.commerce.returns[0].status,'received');assert.throws(()=>D.execute(f.s,agent,'submitRefund',{aftersaleId:f.id,requestId:'early'},NOW),/验收/);});
test('happy return ends only on simulated refund result; second product and payment remain unchanged',()=>{const f=pending(),before=JSON.stringify(f.s.commerce.items[1]),pkg=JSON.stringify(f.s.commerce.packages[1]);assert.equal(f.s.cases.find(c=>c.id===f.caseId).status,'open');f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'refund_succeeded',version:3}).state;assert.equal(f.s.commerce.refunds[0].status,'succeeded');assert.equal(f.s.commerce.refunds[0].amountCents,12900);assert.equal(f.s.commerce.occupancies[0].state,'used');assert.equal(f.s.cases.find(c=>c.id===f.caseId).status,'completed');assert.equal(f.s.cases.find(c=>c.id===f.caseId).feedback,'pending');assert.equal(JSON.stringify(f.s.commerce.items[1]),before);assert.equal(JSON.stringify(f.s.commerce.packages[1]),pkg);assert.equal(f.s.commerce.payments[0].amountCents,17800);});
test('unknown refund queries original request and cannot be done, retried or released',()=>{const f=pending();f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'refund_unknown',version:3}).state;const query=send(f.s,agent,'queryRefund',{aftersaleId:f.id});assert.equal(query.value.requestId,'refund-obligation-1');assert.equal(query.state.commerce.refunds.length,1);assert.throws(()=>D.execute(query.state,agent,'submitRefund',{aftersaleId:f.id,requestId:'another'},NOW),/原|已有|重复/);const t=query.state.tickets.find(t=>t.caseId===f.caseId);assert.throws(()=>D.execute(query.state,agent,'updateTicket',{id:t.id,status:'done',publicText:'已退',evidence:'人工文本'},NOW),/回执|业务|结果/);assert.throws(()=>D.execute(query.state,customer,'feedback',{id:f.caseId,confirmed:true},NOW),/尚未|回执/);f.s=send(f.s,customer,'requestWithdrawal',{aftersaleId:f.id,reason:'不等了'}).state;assert.throws(()=>D.execute(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'withdrawal_confirmed',version:4},NOW),/核实|终止|退款/);assert.equal(f.s.commerce.occupancies[0].state,'reserved');});
test('same obligation never pays twice, repeated and older receipt do not rewrite success',()=>{const f=pending();f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'refund_succeeded',version:3}).state;const r=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'refund_succeeded',version:3});assert.equal(r.state.commerce.occupancies.length,1);assert.equal(r.state.commerce.refunds.length,1);assert.throws(()=>D.execute(r.state,agent,'submitRefund',{aftersaleId:f.id,requestId:'different'},NOW),/原|已有|重复/);assert.throws(()=>D.execute(r.state,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'refund_failed',version:4},NOW),/终态|核实|矛盾/);const old=send(r.state,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'refund_unknown',version:2});assert.equal(old.state.commerce.refunds[0].status,'succeeded');});
test('supplement returns to review without erasing approval history or extending original deadline',()=>{const f=accepted();f.s=send(f.s,manager,'submitReview',{aftersaleId:f.id,decision:'needs_info',reason:'请补充破损说明'}).state;const due=f.s.cases.find(c=>c.id===f.caseId).dueAt;f.s=send(f.s,customer,'submitSupplement',{aftersaleId:f.id,body:'杯身裂痕，附演示凭证',evidenceRef:'DEMO-DAMAGE-001'},NOW+1000).state;assert.equal(f.s.commerce.aftersales[0].status,'awaiting_review');assert.equal(f.s.cases.find(c=>c.id===f.caseId).dueAt,due);assert.equal(f.s.commerce.aftersales[0].reviews.length,1);});
test('rejection or confirmed safe withdrawal releases only unused reservation',()=>{let f=accepted();f.s=send(f.s,manager,'submitReview',{aftersaleId:f.id,decision:'rejected',reason:'模拟核实不满足破损条件'}).state;assert.equal(f.s.commerce.occupancies[0].state,'released');assert.equal(f.s.cases.find(c=>c.id===f.caseId).status,'completed');f=accepted();f.s=send(f.s,customer,'requestWithdrawal',{aftersaleId:f.id,reason:'客户撤回申请'}).state;assert.equal(f.s.commerce.occupancies[0].state,'reserved');f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'withdrawal_confirmed',version:1}).state;assert.equal(f.s.commerce.occupancies[0].state,'released');});
test('notification failure does not change refund success or invent customer satisfaction',()=>{const f=pending();f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'refund_succeeded',version:3}).state;f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'notification_failed',version:4}).state;assert.equal(f.s.commerce.refunds[0].status,'succeeded');assert.equal(f.s.commerce.notifications[0].status,'failed');assert.equal(f.s.cases.find(c=>c.id===f.caseId).feedback,'pending');assert.equal(D.metrics(f.s).service.confirmed,0);});
test('dispute reopens original service, preserving successful refund and consumed allowance',()=>{const f=pending();f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'refund_succeeded',version:3}).state;f.s=send(f.s,customer,'serviceDispute',{caseId:f.caseId,reason:'我没收到款，请核实'}).state;assert.equal(f.s.cases.find(c=>c.id===f.caseId).status,'open');assert.equal(f.s.cases.find(c=>c.id===f.caseId).feedback,'disputed');assert.equal(f.s.commerce.refunds[0].status,'succeeded');assert.equal(f.s.commerce.occupancies[0].state,'used');assert.equal(f.s.commerce.refunds.length,1);assert.equal(D.metrics(f.s).service.refundSucceeded,1);assert.equal(D.metrics(f.s).service.completed,0);});
test('handoff keeps original owner until target accepts with version; old owner loses rights',()=>{const f=approved(),r=send(f.s,agent,'proposeHandoff',{caseId:f.caseId,targetId:'zhou',reason:'交给晚班继续办理',dueAt:NOW+7200000});const h=r.state.commerce.handoffs[0];assert.equal(r.state.cases.find(c=>c.id===f.caseId).ownerId,'lin');assert.throws(()=>D.execute(r.state,agent,'acceptHandoff',{handoffId:h.id,version:h.version},NOW),/目标|无权/);const accepted=send(r.state,other,'acceptHandoff',{handoffId:h.id,version:h.version});assert.equal(accepted.state.cases.find(c=>c.id===f.caseId).ownerId,'zhou');assert.equal(accepted.state.tickets.find(t=>t.caseId===f.caseId).ownerId,'zhou');assert.throws(()=>D.execute(accepted.state,agent,'queryRefund',{aftersaleId:f.id},NOW),/领取|接管|无权/);});
test('handoff updated context requires recheck and timeout preserves responsibility',()=>{const f=approved(),r=send(f.s,agent,'proposeHandoff',{caseId:f.caseId,targetId:'zhou',reason:'继续跟进',dueAt:NOW+60000});const h=r.state.commerce.handoffs[0];r.state.cases.find(c=>c.id===f.caseId).serviceVersion++;assert.throws(()=>D.execute(r.state,other,'acceptHandoff',{handoffId:h.id,version:h.version},NOW),/变化|核对/);const out=send(r.state,manager,'expireHandoffs',{},NOW+60001);assert.equal(out.state.commerce.handoffs[0].status,'expired');assert.equal(out.state.cases.find(c=>c.id===f.caseId).ownerId,'lin');});
test('handoff summary and public projection keep facts and decisions while hiding internal review',()=>{const f=approved();f.s.commerce.aftersales[0].internalNote='PRIVATE-REVIEW';const detail=D.serviceView(f.s,agent,{caseId:f.caseId});assert.equal(detail.handoffSummary.itemName,'原木便携保温杯');assert.ok(detail.handoffSummary.facts);const publicData=JSON.stringify(D.customerView(f.s,'C001'));assert.doesNotMatch(publicData,/PRIVATE-REVIEW|EC-ITEM-009|EC-SO20261005009/);});
test('completeCase, SOP overrides and old intake cannot bypass a formal service result',()=>{const f=approved(),conv=f.s.conversations[0],ticket=f.s.tickets[0];assert.throws(()=>D.execute(f.s,agent,'completeCase',{id:f.caseId,conversationId:conv.id,conclusion:'结束',evidence:'文字'},NOW));assert.throws(()=>D.execute(f.s,agent,'markSop',{conversationId:conv.id,caseId:f.caseId,nodeKey:'result',status:'na',reason:'不适用'},NOW),/业务|回执|已受理/);assert.throws(()=>D.execute(f.s,agent,'updateTicket',{id:ticket.id,status:'done',publicText:'结束',evidence:'文字'},NOW),/业务|回执|结果/);});
test('workflow eval executes all multi-turn branches on isolated copies without mutating business data',()=>{const s=fresh(),before=JSON.stringify({cases:s.cases,commerce:s.commerce});const r=send(s,operator,'runServiceEval',{});assert.equal(r.value.pass,true,JSON.stringify(r.value.rows.filter(x=>!x.pass)));assert.ok(r.value.rows.length>=12);assert.equal(JSON.stringify({cases:r.state.cases,commerce:{...r.state.commerce,evaluations:[]}}),JSON.stringify({cases:s.cases,commerce:{...s.commerce,evaluations:[]}}));assert.equal(JSON.stringify({cases:s.cases,commerce:s.commerce}),before);});
test('knowledge test includes whole workflow and scope/versions invalidate publish',()=>{let s=fresh(),k=s.knowledge[0],draft={...k.live,id:k.id,keywords:k.live.keywords.join(','),scopeItemIds:'EC-ITEM-001',ruleSource:'模拟规则v1',reviewer:'知识运营'};s=send(s,operator,'saveKnowledge',draft).state;s=send(s,operator,'testKnowledge',{id:k.id}).state;assert.equal(s.knowledge[0].validation.passed,true,JSON.stringify(s.knowledge[0].validation));assert.ok(s.knowledge[0].validation.service.rows.length>=12);s.commerce.rules[0].version++;assert.throws(()=>D.execute(s,operator,'publishKnowledge',{id:k.id},NOW),/变化|测试/);});
test('nonknowledge issue cannot be closed by merely publishing knowledge',()=>{let s=fresh();s=send(s,customer,'say',{id:s.conversations[0].id,body:'完全未知问题'}).state;s=send(s,manager,'reviewGap',{id:s.gaps[0].id,status:'confirmed',review:'接口异常',cause:'查询未成功',causeType:'business'}).state;assert.throws(()=>D.execute(s,operator,'linkGap',{id:s.gaps[0].id,knowledgeId:'KB001'},NOW),/整改|场景|知识/);});
test('metric memberships allow all counts to be recalculated and human business steps exclude AI-only',()=>{const f=pending();f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'refund_succeeded',version:3}).state;const m=D.metrics(f.s).service;assert.equal(m.refundSucceeded,1);assert.equal(m.humanInvolved,1);assert.equal(m.aiIndependent,0);for(const [key,ids] of Object.entries(m.metricCaseIds)){assert.equal(m[key],ids.length,key);assert.ok(ids.every(id=>m.rows.some(row=>row.caseId===id)),key);}});
test('unresolved rejection dispute cannot hide a second application under the same case',()=>{const f=accepted();f.s=send(f.s,agent,'claimConversation',{id:f.s.conversations[0].id}).state;f.s=send(f.s,manager,'submitReview',{aftersaleId:f.id,decision:'rejected',reason:'核实不符合样例条件'}).state;f.s=send(f.s,customer,'serviceDispute',{caseId:f.caseId,reason:'请再核实一下'}).state;assert.throws(()=>D.execute(f.s,customer,'previewAftersale',draft(f.s),NOW),/原|异议|复核/);f.s=send(f.s,agent,'resolveServiceDispute',{caseId:f.caseId,body:'已复核原决定，申请材料不满足样例条件',evidenceRef:'DEMO-REVIEW-REJECTION'}).state;assert.equal(f.s.cases.find(c=>c.id===f.caseId).status,'completed');const p=send(f.s,customer,'previewAftersale',draft(f.s)),data={...draft(p.state),token:p.value.token,requestId:'second-valid-application',confirmed:true},r=send(p.state,customer,'confirmAftersale',data);assert.equal(r.state.commerce.aftersales.length,2);assert.notEqual(r.state.commerce.aftersales[0].caseId,r.state.commerce.aftersales[1].caseId);});
test('passing flow evaluation remains publishable and configuration changes invalidate it',()=>{let s=fresh();s=send(s,operator,'saveFlow',{humanWords:s.flow.live.humanWords.join(','),intakeEnabled:true}).state;s=send(s,operator,'testFlow',{}).state;assert.equal(s.flow.validation.passed,true);assert.equal(D.serviceEvalCurrent(s),true);const changed=D.copy(s);changed.flow.draft.humanWords.push('找同事');assert.throws(()=>D.execute(changed,operator,'publishFlow',{},NOW),/变化|测试/);s=send(s,operator,'publishFlow',{}).state;assert.equal(s.flow.live.version,2);});
test('item scope is checked against the full policy question including box aliases',()=>{let s=fresh(),k=s.knowledge[0];s=send(s,operator,'saveKnowledge',{...k.live,id:k.id,keywords:k.live.keywords.join(','),scopeItemIds:itemId}).state;s=send(s,operator,'testKnowledge',{id:k.id}).state;s=send(s,operator,'publishKnowledge',{id:k.id}).state;for(const query of ['收纳袋，退货规则是什么？','收纳盒，退货规则是什么？','杯子和收纳袋的退货政策'])assert.ok(!D.classify(s,query,'C001',NOW).some(r=>r.knowledge?.id===k.id),query);});
test('notification remediation requires the original delivery receipt, not a completed refund',()=>{const f=pending();f.s=send(f.s,customer,'say',{id:f.s.conversations[0].id,body:'保温杯破了想退'}).state;f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'refund_succeeded',version:3}).state;f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'notification_failed',version:4}).state;f.s=send(f.s,agent,'flag',{id:f.s.conversations[0].id}).state;const id=f.s.gaps[0].id;f.s=send(f.s,manager,'reviewGap',{id,status:'confirmed',review:'通知送达失败',cause:'原通知失败',causeType:'notification'}).state;f.s=send(f.s,operator,'linkGap',{id,remediation:'补发原事项通知',scenarioId:'notification-failure'}).state;assert.throws(()=>D.execute(f.s,manager,'acceptGap',{id,acceptance:'示例通过'},NOW),/原|通知|送达/);f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'notification_sent',version:5}).state;f.s=send(f.s,manager,'acceptGap',{id,acceptance:'原通知已有送达回执'}).state;assert.equal(f.s.gaps[0].status,'closed');});
test('policy response uses executable rule amounts and prerequisites even with a misleading draft',()=>{let s=fresh(),k=s.knowledge[0];s=send(s,operator,'saveKnowledge',{...k.live,id:k.id,keywords:k.live.keywords.join(','),scopeItemIds:itemId,answer:'保温杯签收破损可立即退款178元，无需审核，也不用寄回商品。'}).state;s=send(s,operator,'testKnowledge',{id:k.id}).state;assert.equal(s.knowledge[0].validation.passed,true);s=send(s,operator,'publishKnowledge',{id:k.id}).state;s=send(s,customer,'say',{id:s.conversations[0].id,body:'保温杯退货规则是什么？'}).state;const answer=s.conversations[0].messages.findLast(m=>m.role==='bot'&&m.citation);assert.match(answer.body,/129/);assert.match(answer.body,/经理.*审核/);assert.match(answer.body,/寄回.*验收/);assert.doesNotMatch(answer.body,/178|无需审核|不用寄回/);assert.equal(answer.citation.ruleVersion,1);});
test('a policy dependency expiring after testing blocks publication',()=>{let s=fresh(),k=s.knowledge[0];s.commerce.rules[0].expiresAt=new Date(NOW+60000).toISOString();s=send(s,operator,'saveKnowledge',{...k.live,id:k.id,keywords:k.live.keywords.join(','),scopeItemIds:itemId}).state;s=send(s,operator,'testKnowledge',{id:k.id}).state;assert.equal(s.knowledge[0].validation.passed,true);assert.throws(()=>D.execute(s,operator,'publishKnowledge',{id:k.id},NOW+60001),/失效|流程|规则|测试/);});
test('higher-version safety evidence can terminate an already failed refund without changing its outcome',()=>{const f=pending();f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'refund_failed',version:3,safeStopped:false}).state;f.s=send(f.s,customer,'requestWithdrawal',{aftersaleId:f.id,reason:'撤回失败退款申请'}).state;assert.throws(()=>D.execute(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'withdrawal_confirmed',version:4},NOW),/终止|退款/);f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'refund_failed',version:4,safeStopped:true,reason:'核实原执行已终止'}).state;assert.equal(f.s.commerce.refunds[0].status,'failed');f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'withdrawal_confirmed',version:5}).state;assert.equal(f.s.commerce.occupancies[0].state,'released');assert.equal(f.s.commerce.refunds.length,1);});
test('item handoff protects generic commands and enables public replies by the new owner',()=>{const f=approved();f.s=send(f.s,agent,'proposeHandoff',{caseId:f.caseId,targetId:other.id,reason:'晚班接续',dueAt:NOW+3600000}).state;const h=f.s.commerce.handoffs[0];f.s=send(f.s,other,'acceptHandoff',{handoffId:h.id,version:h.version}).state;const convId=f.s.conversations[0].id;assert.throws(()=>D.execute(f.s,agent,'confirmIntent',{conversationId:convId,caseId:f.caseId,kind:'aftersales',title:'旧人修改'},NOW),/接管|领取|无权/);assert.throws(()=>D.execute(f.s,agent,'reply',{id:convId,caseId:f.caseId,body:'旧负责人回复'},NOW),/接管|领取|无权/);f.s=send(f.s,other,'reply',{id:convId,caseId:f.caseId,body:'我是新负责人，会继续核实本事项'}).state;const m=f.s.conversations[0].messages.at(-1);assert.equal(m.author,'客服 02');assert.equal(m.caseId,f.caseId);assert.equal(f.s.conversations[0].ownerId,'lin');});
test('explicit foreign or mismatching orders cannot silently bind a product request to the sample order',()=>{for(const body of ['EC-SO20261005009 保温杯破了想退','EC-SO20261005001 收纳盒坏了想退']){let s=fresh();s=send(s,customer,'say',{id:s.conversations[0].id,body}).state;assert.equal(s.cases.filter(c=>c.service).length,0,body);assert.equal(s.commerce.aftersales.length,0);}});
test('negated defects and completed applications cannot produce phantom pending work',()=>{let s=fresh();s=send(s,customer,'say',{id:s.conversations[0].id,body:'收纳袋不坏，不要退货，我只想查包裹'}).state;assert.equal(s.cases.filter(c=>c.service).length,0);const f=pending();f.s=send(f.s,admin,'applySimulatedReceipt',{aftersaleId:f.id,kind:'refund_succeeded',version:3}).state;assert.throws(()=>D.execute(f.s,customer,'submitSupplement',{aftersaleId:f.id,body:'还没到账，请继续核实'},NOW),/异议|仍需帮助|终结/);});
test('evaluation of a published article uses its live version when no draft exists',()=>{const s=fresh(),r=send(s,operator,'runServiceEval',{knowledgeId:'KB001'});assert.equal(r.value.pass,true,JSON.stringify(r.value.rows.filter(r=>!r.pass)));});
test('routing remediation rechecks every original product matter instead of only the last one',()=>{let s=fresh();s=send(s,customer,'say',{id:s.conversations[0].id,body:'收纳袋没到，保温杯破了想退'}).state;s=send(s,agent,'claimConversation',{id:s.conversations[0].id}).state;const p=send(s,customer,'previewAftersale',draft(s)),r=send(p.state,customer,'confirmAftersale',{...draft(p.state),token:p.value.token,requestId:'two-item-remediation',confirmed:true});s=send(r.state,manager,'submitReview',{aftersaleId:r.value,decision:'rejected',reason:'杯子材料不足'}).state;s=send(s,agent,'flag',{id:s.conversations[0].id}).state;const id=s.gaps[0].id;s=send(s,manager,'reviewGap',{id,status:'confirmed',review:'复验双商品路由',cause:'双诉求漏处理',causeType:'routing'}).state;assert.equal(s.gaps[0].sourceCaseIds.length,2);s=send(s,operator,'linkGap',{id,remediation:'分开核对两商品',scenarioId:'two-items'}).state;assert.throws(()=>D.execute(s,manager,'acceptGap',{id,acceptance:'只办结杯子'},NOW),/原始|完整/);const bag=s.cases.find(c=>c.itemId==='EC-ITEM-002');s=send(s,agent,'resolveLogistics',{caseId:bag.id,body:'已核实该包裹后续配送安排',evidenceRef:'DEMO-BAG-CARRIER'}).state;s=send(s,manager,'acceptGap',{id,acceptance:'两商品均有独立结果依据'}).state;assert.equal(s.gaps[0].status,'closed');});
test('an assigned matter can receive public followup after its conversation closes',()=>{const f=approved();f.s=send(f.s,agent,'closeConversation',{id:f.s.conversations[0].id}).state;f.s=send(f.s,agent,'serviceReply',{caseId:f.caseId,body:'原事项继续跟进，明天反馈仓库核实结果'}).state;const m=f.s.conversations[0].messages.at(-1);assert.equal(m.caseId,f.caseId);assert.equal(m.role,'agent');assert.equal(m.visibility,'public');assert.equal(f.s.cases.find(c=>c.id===f.caseId).status,'open');assert.throws(()=>D.execute(f.s,other,'serviceReply',{caseId:f.caseId,body:'无权回复'},NOW),/接管|领取|无权/);});

test('short policy questions and human suggestions share the same executable policy answer',()=>{let s=fresh(),k=s.knowledge[0];s=send(s,operator,'saveKnowledge',{...k.live,id:k.id,keywords:k.live.keywords.join(','),answer:'立即退款178元，无需审核，也不用寄回商品。'}).state;s=send(s,operator,'testKnowledge',{id:k.id}).state;s=send(s,operator,'publishKnowledge',{id:k.id}).state;for(const body of ['七天退货','退货条件']){s=send(s,customer,'say',{id:s.conversations[0].id,body}).state;const answer=s.conversations[0].messages.findLast(m=>m.citation);assert.match(answer.body,/129/);assert.doesNotMatch(answer.body,/178|无需审核|不用寄回/);assert.equal(answer.citation.ruleVersion,1);}s=send(s,customer,'requestHuman',{id:s.conversations[0].id}).state;s=send(s,agent,'claimConversation',{id:s.conversations[0].id}).state;s=send(s,customer,'say',{id:s.conversations[0].id,body:'七天退货'}).state;const suggestion=D.suggestion(s,s.conversations[0].id,undefined,NOW);assert.match(suggestion.body,/129/);assert.doesNotMatch(suggestion.body,/178|无需审核|不用寄回/);});
