/* Three workspaces over one local scenario model. All dynamic HTML is escaped; uploaded images stay local. */
(function () {
  'use strict';
  const M=window.SupportV2Model,S=window.SupportV2Service,P=window.SupportV2Sop;
  const KEY='support-ecommerce-v2';
  const e=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const t=v=>Number.isFinite(Number(v))?new Date(Number(v)).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'待安排';
  const time=v=>new Date(v).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});
  const isoLocal=milliseconds=>{const d=new Date(milliseconds);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
  const groups={service:'一线客服',aftersales:'售后组',warehouse:'仓库组',finance:'财务组'};
  const stage=v=>S.STAGES[v]||v;
  const orderLabel=v=>({partially_delivered:'部分签收',awaiting_dispatch:'待发货',awaiting_payment:'待支付',delivered:'已签收',cancelled:'已取消'}[v]||v);
  const staffName=id=>state.staff.find(a=>a.id===id)?.name||'待接待';
  const badge=(label,tone='')=>`<span class="badge ${tone}">${e(label)}</span>`;
  const stageBadge=c=>badge(stage(c.stage),c.dispute?.open?'bad':['completed','queried'].includes(c.stage)?'good':['answered','pending_review','waiting_customer','awaiting_refund','refund_unknown','inspection_review','withdrawal_pending'].includes(c.stage)?'warn':'blue');
  const btn=(label,action,attrs='',cls='')=>`<button type="button" class="${cls}" data-action="${action}" ${attrs}>${e(label)}</button>`;
  const empty=(title,text)=>`<div class="empty"><h3>${e(title)}</h3><p>${e(text)}</p></div>`;
  const kv=rows=>`<dl class="kv">${rows.filter(row=>row[1]!==undefined&&row[1]!==null&&row[1]!=='').map(([k,v])=>`<dt>${e(k)}</dt><dd>${e(v)}</dd>`).join('')}</dl>`;
  const field=(name,label,value='',type='text',extras='')=>`<div class="field"><label for="f-${name}">${e(label)}</label><input id="f-${name}" name="${name}" type="${type}" value="${e(value)}" ${extras}></div>`;
  const area=(name,label,value='',extras='')=>`<div class="field"><label for="f-${name}">${e(label)}</label><textarea id="f-${name}" name="${name}" ${extras}>${e(value)}</textarea></div>`;
  const select=(name,label,options,value='',extras='')=>`<div class="field"><label for="f-${name}">${e(label)}</label><select id="f-${name}" name="${name}" ${extras}>${options.map(([v,txt])=>`<option value="${e(v)}" ${String(v)===String(value)?'selected':''}>${e(txt)}</option>`).join('')}</select></div>`;
  const check=(name,label,value)=>`<label class="check-label"><input type="checkbox" name="${name}" ${value?'checked':''}>${e(label)}</label>`;
  let state,corrupt=null,storageAvailable=true,original=null,editingAllowed=true,editingNotice='另一页面正在编辑，本页仅供查看；关闭编辑页后刷新即可继续。';
  try {original=localStorage.getItem(KEY);}catch(err){storageAvailable=false;}
  if(!storageAvailable||original===null)state=M.createState();
  else try {state=JSON.parse(original);S.validateState(state);}catch(err){corrupt=err.message;state=null;}
  const ui={view:'customer',page:'chat',opsPage:'dashboard',deskActor:'lin',opsActor:'operator',caseId:'',queueFilter:'all',conversationId:state?.conversations.find(c=>c.customerId==='C001'&&c.status==='open')?.id||'',modal:'',form:null,replyDraft:null,sopAlt:null};
  const $=s=>document.querySelector(s),app=$('#app'),dialog=$('#dialog');
  function actor(){if(ui.view==='customer')return {id:'C001',role:'customer'};const a=state.staff.find(a=>a.id===(ui.view==='desk'?ui.deskActor:ui.opsActor));return {id:a.id,role:a.role};}
  function run(command,data,who=actor()) {
    if(corrupt||!state)throw new Error('本地记录需要检查，请保留原始记录后处理。');
    if(!editingAllowed)throw new Error(editingNotice);
    if(storageAvailable&&localStorage.getItem(KEY)!==original)throw new Error('记录已在其他页面改变，请刷新后重新核对；本次操作未保存。');
    const result=S.execute(state,who,command,data,Date.now());
    if(storageAvailable){try{const encoded=JSON.stringify(result.state);localStorage.setItem(KEY,encoded);if(localStorage.getItem(KEY)!==encoded)throw new Error('写后读取不一致');original=encoded;}catch(err){throw new Error('本地保存失败，本次修改尚未生效。请减少材料大小或释放浏览器空间后重试。');}}
    state=result.state;return result.value;
  }
  function toast(text,error=false){const el=$('#toast');el.textContent=text;el.className=error?'error':'';el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,4500);}
  function showError(err){if(dialog.open){$('#dialog-error').textContent=err.message||String(err);$('#dialog-error').hidden=false;}else toast(err.message||String(err),true);}
  function modal(title,html,label='服务办理'){ui.modal=label;$('#dialog-title').textContent=title;$('#dialog-label').textContent='服务办理';$('#dialog-error').hidden=true;$('#dialog-body').innerHTML=html;if(!dialog.open)dialog.showModal();}
  function close(){dialog.close();ui.modal='';$('#dialog-error').hidden=true;}
  function currentConversation(){let cv=state.conversations.find(c=>c.id===ui.conversationId&&c.customerId==='C001');if(!cv){cv=state.conversations.find(c=>c.customerId==='C001'&&c.status==='open')||state.conversations.find(c=>c.customerId==='C001');ui.conversationId=cv?.id||'';}return cv;}
  const myOrders=()=>state.orders.filter(o=>o.customerId==='C001');
  const myCases=()=>state.cases.filter(c=>c.customerId==='C001'&&!c.mergedInto);
  function ensureOpen(){let cv=currentConversation();if(!cv||cv.status==='closed'){ui.conversationId=run('newConversation',{}, {id:'C001',role:'customer'});cv=currentConversation();}return cv;}
  function top(){return `<header class="topbar"><div class="brand"><span class="mark" aria-hidden="true"></span>客户服务平台</div><nav class="topnav" aria-label="工作空间">${[['customer','消费者服务'],['desk','客服工作台'],['ops','运营管理']].map(([v,l])=>`<button type="button" data-view="${v}" class="${ui.view===v?'active':''}">${l}</button>`).join('')}</nav><div class="session-label">${ui.view==='customer'?'客户 001':e(staffName(actor().id))}</div></header>`;}
  function subnav(rows,current,attr='data-page'){return `<nav class="subnav" aria-label="功能导航">${rows.map(([p,l])=>`<button type="button" ${attr}="${p}" class="${p===current?'active':''}">${l}</button>`).join('')}</nav>`;}
  function render(){if(corrupt||!state){app.innerHTML=empty('本地记录需要检查','现有数据未被覆盖。请保留浏览器原记录，使用另一浏览器打开本版本，或先导出旧记录再处理。');return;}app.innerHTML=top()+`<main class="page ${ui.view==='desk'||ui.view==='customer'&&ui.page==='chat'?'chat-page':''}">${!editingAllowed?'<div class="notice warn">'+e(editingNotice)+'</div>':''}${ui.view==='customer'?customer():ui.view==='desk'?desk():operations()}${!storageAvailable?'<p class="footer-note">当前浏览器未启用本地保存，关闭窗口后新内容可能丢失。</p>':''}</main>`;const list=$('.messages');if(list)list.scrollTop=list.scrollHeight;}
  function customer(){return `<div class="page-head"><div><p class="eyebrow">CUSTOMER SERVICE</p><h1>${({chat:'咨询与办理',orders:'我的订单',products:'商品与选购',progress:'服务进度'})[ui.page]}</h1><p>查询有依据，办理有进度。未完成的问题可以继续接着处理。</p></div>${btn('联系人工','human','','')}</div>`+subnav([['chat','在线咨询'],['orders','我的订单'],['products','商品选购'],['progress','服务进度']],ui.page)+({chat:chatView,orders:ordersView,products:catalogView,progress:progressView}[ui.page]||chatView)();}
  function legacyReply(m,conv) {
    if(m.role!=='system'||m.kind)return false;
    // Older records identify only the first human reply. Do not guess other senders from their wording.
    return m.caseIds?.some(id=>state.cases.some(c=>c.id===id&&c.firstHumanReplyAt===m.at&&
      conv.messages.filter(other=>other.at===m.at&&other.caseIds?.includes(id)).length===1));
  }
  function conversationMessages(conv) {
    if(!conv)return [];
    return conv.messages.map(m=>legacyReply(m,conv)?{...m,role:'agent'}:m).slice().sort((a,b)=>a.at-b.at);
  }
  function messageView(m){const label=m.role==='customer'?(ui.view==='customer'?'您':'客户'):m.role==='agent'?(m.senderName||'人工客服'):m.role==='assistant'?'AI 客服':'系统通知',avatar=m.role==='customer'?'客户':m.role==='assistant'?'AI':'客服';return `<div class="message ${e(m.role)}" data-message-id="${e(m.id)}">${m.role!=='system'?`<span class="avatar" aria-hidden="true">${avatar}</span>`:''}<div class="message-content"><div class="message-sender">${e(label)}</div><div class="bubble">${e(m.body)}</div>${m.source?`<span class="source">依据：${e(m.source)}</span>`:''}${m.action&&ui.view==='customer'?`<div class="message-actions">${btn(({orders:'选择订单',products:'查看商品',coupon:'优惠查询',progress:'查看进度',aftersales:'核对售后申请',cancel_order:'取消订单',change_address:'修改地址',invoice:'发票服务',repair:'维修服务',price_protection:'价保核实'})[m.action]||'继续办理','message-action',`data-kind="${e(m.action)}" data-order="${e(m.orderId||'')}" data-item="${e(m.itemId||'')}" data-case="${e(m.caseIds?.[0]||'')}"`,'small')}</div>`:''}<div class="message-meta">${e(time(m.at))}${m.caseIds?.length?' · '+m.caseIds.map(cid=>`<button class="link" data-action="case" data-case="${e(cid)}">${e(cid)}</button>`).join('、'):''}</div></div></div>`;}
  function mini(c){return `<div class="case-mini"><div class="row between"><span class="case-id">${e(c.id)}</span>${stageBadge(c)}</div><h4>${btn(c.title,'case',`data-case="${e(c.id)}"`,'link')}</h4><div class="small muted">${e(groups[c.groupOwnerId]||'服务组')} · ${c.status==='completed'?'已保留处理记录':'下次反馈 '+e(t(c.nextAt))}</div></div>`;}
  function chatView(){const cv=currentConversation(),pending=myCases().filter(c=>c.status!=='completed'&&!['withdrawn','rejected'].includes(c.stage));return `<div class="customer-layout"><section class="panel chat-panel"><div class="chat-head"><div><h3>在线客服</h3><div class="chat-status"><span class="dot"></span>${cv?.status==='closed'?'本次会话已结束':cv?.mode==='human'?'由 '+e(staffName(cv.ownerId))+' 接待':cv?.mode==='queue'?'等待人工接续，事项已保留':'智能接待，可随时转人工'}</div></div><div class="row">${btn('历史咨询','history','','quiet small')}${btn('新建咨询','new-chat','','small')}</div></div><div class="messages self-right" aria-live="polite">${conversationMessages(cv).map(messageView).join('')||empty('开始咨询','描述您需要了解或办理的问题。')}</div><div class="composer"><div class="quick-actions">${btn('查订单','goto-orders')}${btn('申请售后','application')}${btn('优惠查询','coupon')}${btn('服务进度','goto-progress')}</div><form id="chat-form"><textarea aria-label="咨询内容" name="body" id="chat-input" placeholder="例如：杯子怎么清洗？订单的另一个包裹到哪了？" required maxlength="4000"></textarea><button class="primary" type="submit">发送</button></form><div class="composer-hint">Enter 发送 · Shift + Enter 换行。业务申请在核对确认后提交。</div></div></section><aside class="customer-aside stack"><div class="hero-note"><h3>已有信息不必重复填写</h3><p>选择订单后，可接着查询包裹、整理申请或跟进原事项。</p>${btn('查看我的订单','goto-orders')}</div><section class="panel"><div class="panel-head"><h3>正在跟进</h3>${badge(pending.length+'项')}</div><div class="panel-body">${pending.slice(0,4).map(mini).join('')||'<p class="small muted">目前没有待处理事项。</p>'}</div></section><section class="panel"><div class="panel-body"><div class="side-grid"><div><div class="side-stat">${myOrders().length}</div><div class="small muted">本人订单</div></div><div><div class="side-stat">${state.applications.filter(a=>a.customerId==='C001').length}</div><div class="small muted">服务申请</div></div></div><hr class="rule"><p class="small muted">受理、审核与执行分别展示；如对结果有异议，可继续原事项复核。</p></div></section></aside></div>`;}
  function ordersView(){return `<div class="order-grid">${myOrders().map(o=>{const pay=state.payments.find(p=>p.orderId===o.id);return `<section class="panel order-card"><div class="order-top row between"><span class="order-id">${e(o.id)}</span>${badge(orderLabel(o.status),o.status==='cancelled'?'':'blue')}</div>${state.items.filter(i=>i.orderId===o.id).map(i=>{const p=state.packages.find(p=>p.itemIds.includes(i.id));return `<div class="order-item"><div class="product-icon">${i.skuId==='EC-SKU-CUP'?'保温杯':i.skuId==='EC-SKU-BAG'?'收纳袋':'收纳盒'}</div><div class="grow"><div class="row between"><h3>${e(i.name)}</h3><span>${M.amount(i.paidCents)}</span></div><div class="muted">${e(i.variant)} · 数量 ${i.quantity}</div><div class="small muted">${e(S.packLabel(p))}${p.tracking?' · '+e(p.tracking):''}</div><div class="actions">${btn('查询物流','query-logistics',`data-order="${e(o.id)}" data-item="${e(i.id)}"`,'small')}${btn('咨询此商品','context',`data-order="${e(o.id)}" data-item="${e(i.id)}"`,'small')}${o.status!=='cancelled'?btn('申请售后','application',`data-order="${e(o.id)}" data-item="${e(i.id)}"`,'small'):''}</div></div></div>`;}).join('')}<div class="order-footer"><div class="row between"><span class="small muted">${e(S.payLabel(pay))}</span>${pay?.queryStatus==='ok'&&pay.status==='paid'?`<span>实付 <strong class="price">${M.amount(pay.amountCents)}</strong></span>`:''}</div><div class="actions">${btn('支付核实','query-order',`data-order="${e(o.id)}"`,'small')}${o.status!=='cancelled'?btn('取消订单','application',`data-kind="cancel_order" data-order="${e(o.id)}"`,'small')+btn('修改地址','application',`data-kind="change_address" data-order="${e(o.id)}"`,'small'):''}${btn('发票 / 价保 / 维修','other-services',`data-order="${e(o.id)}"`,'small')}</div><div class="address-line">收货信息：${e(o.address.name)} · ${e(o.address.phone.replace(/(\d{3})\d{4}(\d+)/,'$1****$2'))} · ${e(o.address.text)}</div></div></section>`;}).join('')}</div>`;}
  function catalogView(){return `<div class="catalog-grid">${state.catalog.map((p,i)=>`<article class="panel"><div class="catalog-art" aria-hidden="true"><div class="catalog-shape ${['cup','bag','box'][i]}"></div></div><div class="catalog-body"><div class="row between"><h3>${e(p.name)}</h3><strong class="price">${M.amount(p.priceCents)}</strong></div><p>${e(p.description)}</p><div class="attributes">${p.attributes.map(a=>`<span class="attribute">${e(a)}</span>`).join('')}</div><p>${p.variants.map(v=>e(v.label)+' · '+(v.stock>0?'有货':'暂时无货')).join('<br>')}</p><div class="actions">${btn('了解使用方式','ask-product',`data-text="${e(p.name+'怎么清洗')}"`,'small')}${btn('帮我选规格','ask-product',`data-text="${e(p.name+'适合什么用途，怎么选')}"`,'small')}</div><span class="source">${e(p.source)} · ${e(t(p.queriedAt))}</span></div></article>`).join('')}</div><div class="notice" style="margin-top:20px">商品属性与活动规则分别核对。${btn('查询本人订单的优惠资格','coupon','','link')}</div>`;}
  function progressView(){const rows=myCases();return rows.length?`<div class="progress-grid">${rows.map(c=>`<article class="panel progress-card"><div class="row between"><span class="case-id">${e(c.id)}</span>${stageBadge(c)}</div><h3>${e(c.title)}</h3><p class="desc">${e(c.description||c.result?.body?.slice(0,80)||'已保留本次咨询与处理记录。')}</p><div class="small muted" style="margin-top:12px">${e(groups[c.groupOwnerId]||'客服组')} · ${c.ownerId?e(staffName(c.ownerId)):'待责任组接续'}${c.status!=='completed'?'<br>下次反馈 '+e(t(c.nextAt)):''}</div><div class="actions">${btn('查看进度与操作','case',`data-case="${e(c.id)}"`,'small primary')}</div></article>`).join('')}</div>`:empty('暂无服务事项','咨询问题或确认申请后，可以在这里查看进度和后续安排。');}
  const application=c=>state.applications.find(r=>r.caseId===c.id);
  const refund=c=>state.refunds.find(r=>r.caseId===c.id);
  const returnOf=c=>state.returns.find(r=>r.applicationId===c.applicationId);
  function history(c,conv=null){
    const shown=conv?conversationMessages(conv).filter(m=>m.role==='agent'&&m.caseIds?.includes(c.id)):[];
    const rows=c.history.filter(h=>!shown.some(m=>m.at===h.at&&m.body===h.text));
    return `<ul class="timeline">${rows.length?rows.slice().reverse().map(h=>`<li><span class="time">${e(t(h.at))}</span><div>${h.kind==='reply'?e(h.senderName||'人工客服')+'：':''}${e(h.text||stage(h.stage))}</div></li>`).join(''):'<li>已保留原始咨询，尚无新的业务办理进展。</li>'}</ul>`;
  }
  function evidence(ids=[]){return `<div class="attachments">${ids.map(id=>state.attachments.find(x=>x.id===id)).filter(Boolean).map(f=>`<div class="attachment"><img src="${e(f.dataUrl)}" alt="${e(f.name)}"><div class="file-name">${e(f.name)}</div></div>`).join('')}</div>`;}
  function facts(c){const r=application(c),f=refund(c),ret=returnOf(c),o=state.orders.find(o=>o.id===c.orderId),i=state.items.find(i=>i.id===c.itemId);return kv([['事项编号',c.id],['订单',o?.id],['商品',i?i.name+' · '+i.variant:undefined],['申请类型',r?S.TYPES[r.type]:S.TYPES[c.type]],['申请原因',r?.reason||c.description],['目标规格',r?.targetVariant],['缺失内容',r?.missingName?`${r.missingScope==='part'?'配件':'整件商品'}：${r.missingName} × ${r.missingQuantity}`:undefined],['发票抬头',r?.invoiceTitle],['接收邮箱',r?.email],['价格依据',r?.comparison],['审核结论',r?.review?.reason],['核定退款金额',r?.amountCents?M.amount(r.amountCents):f?M.amount(f.amountCents):undefined],['退款请求',f?.requestId],['退款回执',f?.receiptId],['退回运单',ret?.tracking?ret.carrier+' · '+ret.tracking:undefined],['规则依据',r?.policy?.source?`${r.policy.source} v${r.policy.version}`:undefined],['业务责任组',groups[c.groupOwnerId]],['服务责任人',c.ownerId?staffName(c.ownerId):'责任组待分配'],['下次反馈',c.status!=='completed'?t(c.nextAt):undefined],['用户反馈',({pending:'尚未反馈',resolved:'明确表示已解决',unresolved:'明确表示未解决'})[c.feedback]]])+ (r?.attachmentIds.length?`<h4 class="section-title">已提交材料</h4>${evidence(r.attachmentIds)}`:'')+(r?.supplements?.length?`<h4 class="section-title">补充记录</h4>${r.supplements.map(x=>`<p>${e(x.note)} <span class="muted small">${e(t(x.at))}</span></p>`).join('')}`:'')+(c.dispute?.open?`<div class="notice warn">异议仍在复核：${e(c.dispute.reason)}</div>`:'');}
  function customerCaseActions(c){const r=application(c),f=refund(c),ret=returnOf(c);let html='';if(!r&&!c.changeId&&['return_refund','refund_only','exchange','reship','cancel_order','change_address','invoice','price_protection','repair'].includes(c.type))html+=btn('核对并继续申请','application',`data-case="${e(c.id)}" data-kind="${e(c.type)}" data-order="${e(c.orderId)}" data-item="${e(c.itemId)}"`,'primary');if(r){if(r.stage==='awaiting_return')html+=btn('填写寄回运单','command',`data-command="submitReturn" data-case="${e(c.id)}"`,'primary');if(['waiting_customer','inspection_review'].includes(r.stage))html+=btn('补充材料','supplement',`data-case="${e(c.id)}"`,'primary');if(r.stage==='rejected')html+=btn('申请复核','command',`data-command="requestReview" data-case="${e(c.id)}"`);if(!['completed','withdrawn','withdrawal_pending','rejected'].includes(r.stage))html+=btn('申请撤回','command',`data-command="requestWithdrawal" data-case="${e(c.id)}"`);}
    if(f?.requestId)html+=btn('查询原退款','command',`data-command="queryRefund" data-case="${e(c.id)}"`);html+=btn('反馈是否解决','feedback',`data-case="${e(c.id)}"`);
    return (ret?`<div class="preview-block"><h4>本申请寄回指引</h4>${kv([['收件人',ret.instructions.contact],['联系电话',ret.instructions.phone],['寄回地址',ret.instructions.address],['运费方案',ret.instructions.fee],['寄回要求',ret.instructions.notes]])}</div>`:'')+(r?.stage==='awaiting_fulfillment'?'<div class="notice">正在按申请类型协调履约。尚无新包裹、开票、补差或维修完成回执，不能认定业务已经完成。</div>':'')+`<div class="actions">${html}</div>`;}
  function caseModal(caseId){const c=state.cases.find(c=>c.id===caseId);if(!c||ui.view==='customer'&&c.customerId!=='C001')throw Error('事项不存在或不属于当前客户');if(c.mergedInto)return caseModal(c.mergedInto);ui.caseId=c.id;modal(c.title,`<div class="row between"><span class="case-id">${e(c.id)}</span>${stageBadge(c)}</div><div class="section-title">事项信息</div>${facts(c)}${ui.view==='customer'?customerCaseActions(c):staffActions(c)}<h4 class="section-title">处理记录</h4>${history(c)}${state.callbacks.filter(cb=>cb.caseId===c.id&&cb.status==='scheduled').map(cb=>`<div class="notice">已安排 ${e(t(cb.nextAt))} 回访：${e(cb.reason)}</div>`).join('')}`,'case');}
  function staffActions(c){const a=actor(),r=application(c),f=refund(c),h=state.handoffs.find(h=>h.caseId===c.id&&h.status==='pending');let rows=[];const add=(label,command,cls='')=>rows.push(btn(label,'command',`data-command="${command}" data-case="${e(c.id)}"`,cls));
    if(a.role==='agent'&&!c.ownerId)add('接管事项','claim','primary');
    if(h?.targetId===a.id){add('确认接收转派','acceptHandoff','primary');add('拒收并保留原责任','rejectHandoff');}
    const owns=a.role==='manager'||a.role==='agent'&&c.ownerId===a.id||['warehouse','finance'].includes(a.role)&&c.groupOwnerId===state.staff.find(x=>x.id===a.id).team;
    if(!owns)return `<div class="actions">${rows.join('')}</div>`;
    if(a.role==='agent'||a.role==='manager'){add('内部备注','note');add('安排后续反馈','followup');add('安排回访','scheduleCallback');add('转派接续客服','handoff');add('登记质量问题','flagCase');if(['human','knowledge','clarification','consultation','complaint'].includes(c.type)&&c.status!=='completed')add('登记处理结论','completeInquiry');if(!r&&!c.changeId&&c.orderId)rows.push(btn('协助整理申请','prefill',`data-case="${e(c.id)}"`));}
    if(r){if(a.role==='manager'&&r.stage==='pending_review'){add('审核通过','approve','primary');add('审核不通过','reject');}if(['pending_review','inspection_review','awaiting_fulfillment'].includes(r.stage))add('请求补充资料','requestSupplement');if(a.role==='manager'&&r.withdrawal?.status==='pending')add('核实撤回并继续办理','denyWithdrawal');if(['manager','warehouse'].includes(a.role)){if(r.stage==='returning')add('确认仓库收货','receiveReturn','primary');if(r.stage==='received')add('登记验收结果','inspect','primary');if(r.stage==='inspection_review')add('完成验收复核','resolveInspection','primary');}}
    if(f&&a.role==='finance'){if(['not_submitted','failed'].includes(f.status))add('提交原退款请求','submitRefund','primary');if(f.requestId){add('查询原退款结果','queryRefund');add('登记渠道回执','recordRefundReceipt','primary');}}
    if(c.type==='logistics'&&['agent','warehouse','manager'].includes(a.role)&&c.status!=='completed')add('登记物流核实结论','resolveLogistics','primary');
    if(c.type==='payment'&&a.role==='finance')add('登记支付核实结果','resolvePayment','primary');
    if(c.dispute?.open&&c.result?.valid)add('登记异议复核结论','resolveDispute');
    for(const cb of state.callbacks.filter(cb=>cb.caseId===c.id&&cb.status==='scheduled'))rows.push(btn('登记回访结果','command',`data-command="callbackResult" data-case="${e(c.id)}" data-callback="${e(cb.id)}"`));
    if(['manager','agent'].includes(a.role)){const notification=state.notifications.filter(n=>n.caseId===c.id).at(-1);if(notification)rows.push(btn('核实通知状态','command',`data-command="notificationResult" data-case="${e(c.id)}" data-notification="${e(notification.id)}"`));}
    return `<div class="actions">${rows.join('')}</div>`+(h?`<p class="small muted">转派 ${e(staffName(h.targetId))} 待接收。当前责任人：${e(staffName(c.ownerId))}。</p>`:'');}
  function deskRows(){const a=actor();return state.cases.filter(c=>!c.mergedInto).filter(c=>ui.queueFilter==='mine'?c.ownerId===a.id:ui.queueFilter==='pending'?c.status!=='completed'&&!['withdrawn','rejected'].includes(c.stage):ui.queueFilter==='group'?c.groupOwnerId===state.staff.find(x=>x.id===a.id).team:true);}
  function queueContents(rows,currentId,dialogView=false){return `<div class="panel-head"><h3>服务队列</h3>${badge(rows.length+'项')}</div><div class="panel-body">${select(dialogView?'queueDialogFilter':'queueFilter','显示范围',[['all','全部事项'],['mine','我负责的'],['group','本责任组'],['pending','未完成事项']],ui.queueFilter)}</div>${rows.map(x=>`<button class="case-row ${x.id===currentId?'active':''}" data-action="select-case" data-case="${e(x.id)}"><div class="row between"><span class="case-id">${e(x.id)}</span>${stageBadge(x)}</div><strong>${e(x.title)}</strong><span class="small muted">${e(groups[x.groupOwnerId]||'服务组')} · ${e(x.ownerId?staffName(x.ownerId):'待分配')}</span></button>`).join('')||empty('队列暂无事项','消费者提出问题或确认申请后会显示在这里。')}`;}
  function openDeskQueue(){modal('服务队列',queueContents(deskRows(),ui.caseId,true),'queue');}
  function desk(){const a=actor(),rows=deskRows();let c=rows.find(c=>c.id===ui.caseId)||rows[0];if(c)ui.caseId=c.id;
    return `<div class="page-head"><div><p class="eyebrow">SERVICE WORKBENCH</p><h1>事项与协作</h1><p>接待责任与业务办理责任分别保留，转派确认前不丢失跟进人。</p></div><div class="actor-select">${select('deskActor','当前处理角色',state.staff.filter(x=>x.role!=='operator').map(x=>[x.id,x.name]),ui.deskActor)}${a.role==='agent'?btn(state.staff.find(x=>x.id===a.id).available?'设为离线':'设为在线','presence','','small'):''}${btn('服务队列','desk-queue','','small compact-queue-actions')}</div></div><div class="workbench"><aside class="panel queue-panel">${queueContents(rows,c?.id)}</aside><section class="work-main">${c?deskDetail(c):'<div class="panel">'+empty('选择需要跟进的事项','可以处理用户诉求、受理资料、业务回执和后续反馈。')+'</div>'}</section></div>`;}
  function deskContext(c,conv){return `${state.callbacks.filter(cb=>cb.caseId===c.id&&cb.status==='scheduled').map(cb=>`<div class="notice">已安排 ${e(t(cb.nextAt))} 回访：${e(cb.reason)}</div>`).join('')}<div class="business-history"><h4 class="section-title">业务事件</h4>${history(c,conv)}</div><h4 class="section-title">事项信息</h4>${facts(c)}${returnOf(c)?`<h4 class="section-title">退回验收</h4>${kv([['寄回地址',returnOf(c).instructions.address],['最近验收',returnOf(c).inspection?.reason]])}`:''}<h4 class="section-title">内部备注</h4>${c.notes.map(n=>`<p class="notes">${e(n.body)}<br><span class="small muted">${e(staffName(n.actorId))} · ${e(t(n.at))}</span></p>`).join('')||'<p class="muted small">暂无内部备注。</p>'}`;}
  function deskDetail(c){
    const a=actor(),conv=state.conversations.find(v=>v.id===c.conversationIds.at(-1));
    return `<div class="desk-columns"><section class="panel desk-chat"><div class="panel-head"><h3>会话记录</h3><div class="row">${btn('处理面板','desk-workflow',`data-case="${e(c.id)}"`,'small compact-workflow-actions')}${conv&&['agent','manager'].includes(a.role)?btn('结束本次接待','command',`data-command="closeConversation" data-case="${e(c.id)}"`,'quiet small'):''}</div></div><div class="panel-body messages desk-history">${conversationMessages(conv).map(messageView).join('')||'<p class="muted small">暂无会话消息。</p>'}</div>${a.role==='agent'&&c.ownerId===a.id?replyForm(c,a):''}</section><aside class="panel desk-workflow" aria-label="服务处理面板"><div class="panel-head"><h3>服务处理</h3></div><div class="panel-body workflow-body">${deskWorkflow(c,conv)}</div></aside></div>`;
  }
  function deskWorkflow(c,conv){
    return `<div class="workflow-case"><div class="row between"><span class="case-id">${e(c.id)}</span>${stageBadge(c)}</div><h2>${e(c.title)}</h2><p class="small muted">${e(c.ownerId?staffName(c.ownerId)+' 跟进':'待客服接管')}</p></div>${c.type==='clarification'&&c.status==='completed'?`<div class="notice"><strong>处理结论</strong><p class="break">${e(c.result?.reason||'已登记处理结果。')}</p></div>`:''}${sopAxis(P.build(state,c.id,{agentId:actor().id,fmt:t}))}<section class="workflow-actions"><h4>办理操作</h4>${staffActions(c)}</section><details class="workflow-context"><summary>关联信息与业务事件</summary>${deskContext(c,conv)}</details>`;
  }
  const SOP_TAG={current:'进行中',async:'会后跟进',skip:'未触发'};
  function sopRow(n,cls=''){
    const tag=n.status==='skip'&&n.key.includes('.')?'已终止':SOP_TAG[n.status]||'';
    return `<li class="sop-row st-${n.status} ${cls} ${n.lit?'lit':''} ${n.status==='current'?'is-current':''}" ${n.status==='current'?'aria-current="step"':''}><span class="sop-dot s-${n.status}" aria-hidden="true"></span><div class="sop-line"><span class="sop-name">${e(n.name)}</span>${tag?`<span class="sop-tag t-${n.status}">${tag}</span>`:''}${n.time?`<span class="sop-time">${e(n.time)}</span>`:''}</div>${n.note?`<p class="sop-note break">${e(n.note)}</p>`:''}</li>`;
  }
  function sopAxis(m){
    if(!m)return '';
    const stage=s=>`<li class="sop-stage ${s.lit?'lit':''}"><span class="sop-stage-num">${s.num}</span>${s.title}${s.meta?`<span class="small muted">${e(s.meta)}</span>`:''}</li>`;
    const intent=it=>`<li class="sop-row sop-intent st-${it.status} ${it.lit?'lit':''} ${it.hit?'is-hit':''}"><span class="sop-tick" aria-hidden="true"></span>${it.hit&&it.steps.length?'<span class="sop-sub first" aria-hidden="true"></span>':''}<span class="sop-dot s-${it.status}" aria-hidden="true"></span><div class="sop-line"><span class="sop-name">${e(it.name)}</span>${it.hit?'<span class="sop-tag t-hit">命中</span>':''}</div>${it.hit?'':`<p class="sop-note">${e(it.stepsText)}</p>`}</li>${it.steps.map((x,i)=>sopRow(x,'sop-step'+(i===it.steps.length-1?' last-step':''))).join('')}`;
    const group=g=>`<li class="sop-branch ${g.hit?'is-hit':''}"><details ${g.hit?'open':''}><summary class="sop-group ${g.lit?'lit':''}"><span class="sop-tick" aria-hidden="true"></span><span class="sop-mark" aria-hidden="true"></span><span class="sop-group-name">${e(g.name)}</span><span class="small muted">${g.count} 个意图${g.hit?' · 已命中':''}</span><span class="sop-chev" aria-hidden="true"></span><span class="sop-group-names">${e(g.intents.map(it=>it.name).join(' · '))}</span></summary><ol class="sop-axis sop-intents">${g.intents.map(intent).join('')}</ol></details></li>`;
    const [s1,s2,s3,s4]=m.stages;
    return `<section class="sop" aria-label="服务 SOP"><div class="row between"><h4>服务 SOP</h4>${badge(m.intent?m.intent.name:'待澄清',m.intent?'good':'warn')}</div><div class="sop-progress" role="progressbar" aria-label="SOP 进度" aria-valuemin="0" aria-valuemax="${m.total}" aria-valuenow="${m.done}"><span style="width:${Math.round(m.done/m.total*100)}%"></span></div><p class="small muted">已完成 ${m.done} / ${m.total} 个节点 · ${m.current?'当前：'+e(m.currentLabel):'已全部完成'}</p><p class="sop-legend small muted"><span class="sop-dot s-done"></span>已完成<span class="sop-dot s-current"></span>进行中<span class="sop-dot s-next"></span>待执行<span class="sop-dot s-async"></span>会后跟进<span class="sop-dot s-dim"></span>未命中</p><ol class="sop-axis">${stage(s1)}${s1.nodes.map((n,i)=>sopRow(n,i===0?'first':'')).join('')}${stage(s2)}${s2.nodes.map(n=>sopRow(n)).join('')}${stage(s3)}${s3.groups.map(group).join('')}${stage(s4)}${s4.nodes.map((n,i)=>sopRow(n,i===s4.nodes.length-1?'last':'')).join('')}</ol></section>`;
  }
  function replyForm(c,a){
    const m=P.build(state,c.id,{agentId:a.id,fmt:t}),p=m?.prefill,draft=ui.replyDraft?.caseId===c.id?ui.replyDraft:null;
    // Without a template, a direct reply on a say-node completes that node.
    const node=draft?draft.sopNode:p&&p.kind==='say'&&!p.options.length?p.node:'';
    return `<form id="reply-form" class="panel-body reply-form"><input type="hidden" name="caseId" value="${e(c.id)}"><input type="hidden" name="sopNode" value="${e(node)}">${sopPrefill(c,m)}${area('body','公开回复',draft?.body||'','required maxlength="4000"')}<button type="submit" class="primary">确认发送</button><span class="help">由当前客服确认后发送，不自动替用户作业务确认。</span></form>`;
  }
  function sopPrefill(c,m){
    const p=m?.prefill;
    if(!m)return '';
    if(!p)return '<div class="sop-prefill quiet"><strong>本次服务 SOP 已走完</strong><span class="small muted">确认客户没有其他问题后，可以结束本次接待。</span></div>';
    const i=ui.sopAlt?.caseId===c.id&&ui.sopAlt.node===p.node?ui.sopAlt.index%Math.max(p.options.length,1):0;
    const data=`data-case="${e(c.id)}" data-node="${e(p.node)}" data-alt="${i}"`;
    const head=label=>`<div class="sop-prefill-head"><span class="sop-prefill-label">${label} · 节点「${e(p.label)}」</span>${p.options.length>1&&!p.asked?`<span class="small muted">第 ${i+1} / ${p.options.length} 条</span>`:''}</div>`;
    if(!p.options.length)return `<div class="sop-prefill quiet">${head('当前节点')}<p class="sop-prefill-guide">${e(p.guidance)}${p.kind==='say'?' 直接在下方回复即记为完成本节点。':''}</p></div>`;
    if(p.asked)return `<div class="sop-prefill quiet">${head('已追问')}<p class="sop-prefill-guide">已发送，等待客户补充。${e(p.guidance)}</p><div class="sop-prefill-actions">${btn('再次填入话术','sop-fill',data,'small')}</div></div>`;
    return `<div class="sop-prefill">${head('话术预填')}<p class="sop-prefill-text break">${e(p.options[i])}</p><div class="sop-prefill-actions">${btn('采用并发送','sop-send',data,'primary small')}${btn('填入修改','sop-fill',data,'small')}${p.options.length>1?btn('换一条','sop-alt',data,'quiet small'):''}<span class="help">人工确认后才发出</span></div>${m.awaitingCustomer?'<p class="sop-prefill-note small muted">客户还没有回复上一条消息。</p>':''}</div>`;
  }
  function keepReplyDraft(caseId){const f=$('#reply-form'),body=f?.elements?.body?.value;if(typeof body==='string'&&body.trim())ui.replyDraft={caseId,body,sopNode:f.elements.sopNode?.value||''};}
  function operations(){return `<div class="page-head"><div><p class="eyebrow">SERVICE OPERATIONS</p><h1>服务运营</h1><p>场景规则、知识版本与处理结果使用同一份事项记录。</p></div><div class="actor-select">${select('opsActor','当前管理角色',[['operator','知识运营'],['manager','售后主管']],ui.opsActor)}</div></div>${subnav([['dashboard','服务看板'],['policies','场景配置'],['knowledge','知识库'],['quality','质检整改'],['settings','接待设置']],ui.opsPage,'data-ops-page')}${({dashboard:dashboard,policies:policiesView,knowledge:knowledgeView,quality:qualityView,settings:settingsView}[ui.opsPage]||dashboard)()}`;}
  function dashboard(){const m=S.metrics(state,actor()),rate=(n)=>m.total?Math.round(n/m.total*100)+'%':'—';return `<div class="stats">${[['有效事项',m.total,'同一事项跨会话不重复计数'],['有据解决',m.resolved,'解决率 '+rate(m.resolved)],['AI独立解决',m.independent,'独立解决率 '+rate(m.independent)],['待确认答复',m.waitingFeedback,'仅已回答不计为问题解决'],['待处理事项',m.pending,'申请、外部结果与反馈分别跟踪'],['超过反馈时间',m.overdue,'从事项下钻查看责任与安排'],['未结异议',m.disputes,'原问题重开，不重复执行退款'],['退款结果未知',m.unknownRefunds,'保留原请求和商品占用']].map(([label,n,note])=>`<div class="panel stat"><div class="label">${label}</div><div class="value">${n}</div><div class="note">${note}</div></div>`).join('')}</div><p class="small muted">观察范围：${e(t(m.from))} 至 ${e(t(m.observedAt))}，共 ${m.total} 个有效事项。人工审批、仓库与财务办理均排除AI独立解决。当前数据为本地运行记录，不代表商家经营效果。</p><section class="panel"><div class="panel-head"><h3>事项明细</h3></div><div class="table-wrap"><table><thead><tr><th>事项</th><th>状态</th><th>办理方式</th><th>解决证据</th><th>用户反馈</th><th>操作</th></tr></thead><tbody>${state.cases.filter(c=>!c.mergedInto).map(c=>`<tr><td><span class="list-title">${e(c.title)}</span><span class="small muted">${e(c.id)}</span></td><td>${stageBadge(c)}</td><td>${c.humanTouched?'人工协作':'AI处理'}</td><td>${m.caseIds.includes(c.id)?'符合该诉求的完成证据':c.result?.kind==='answer'?'已答复，待确认':'尚未具备'}</td><td>${({pending:'未反馈',resolved:'已解决',unresolved:'未解决'})[c.feedback]}</td><td>${btn('查看','case',`data-case="${e(c.id)}"`,'small')}</td></tr>`).join('')||'<tr><td colspan="6">暂无业务事项。</td></tr>'}</tbody></table></div></section>`;}
  function policiesView(){return `<div class="notice">维护每种诉求的材料、责任组、寄回条件与反馈安排。草稿需校验后发布；已受理申请继续使用当时确认的规则快照。</div><section class="panel"><div class="table-wrap"><table><thead><tr><th>服务场景</th><th>当前规则</th><th>材料与寄回</th><th>责任与反馈</th><th>变更状态</th><th>操作</th></tr></thead><tbody>${state.policies.map(p=>`<tr><td><strong>${e(p.live.title)}</strong></td><td>v${p.live.version} · ${p.live.enabled?'接受新申请':'暂不受理'}</td><td>${p.live.materialRequired?'需要材料':'按需补充'}<br>${p.live.requiresReturn?'需寄回验收':'不经寄回流程'}</td><td>${e(groups[p.live.team])}<br>${p.live.feedbackHours}小时内反馈</td><td>${p.draft?'有待发布草稿':'当前已生效'}${p.validation?'<br>'+badge(p.validation.passed?'校验通过':'校验未通过',p.validation.passed?'good':'bad'):''}</td><td>${btn('编辑配置','policy',`data-type="${e(p.id)}"`,'small')}</td></tr>`).join('')}</tbody></table></div></section>`;}
  function knowledgeView(){return `<div class="row between" style="margin-bottom:16px"><p class="muted">静态知识负责解释，订单支付与物流事实从业务记录查询。</p>${actor().role==='operator'?btn('新增知识','knowledge','','primary'):''}</div><section class="panel"><div class="table-wrap"><table><thead><tr><th>知识内容</th><th>依据来源</th><th>生效版本</th><th>草稿与验证</th><th>操作</th></tr></thead><tbody>${state.knowledge.map(k=>`<tr><td><strong>${e((k.draft||k.live).title)}</strong><br><span class="small muted">${e((k.draft||k.live).question)}</span></td><td>${e((k.live||k.draft).source)}</td><td>${k.disabled?'已停用':k.live?'v'+k.live.version:'尚未发布'}</td><td>${k.draft?'有草稿':'无待发布变更'}${k.validation?'<br>'+badge(k.validation.passed?'正反例通过':'校验未通过',k.validation.passed?'good':'bad'):''}</td><td>${actor().role==='operator'?btn('编辑 / 验证','knowledge',`data-id="${e(k.id)}"`,'small'):'仅查看'}</td></tr>`).join('')}</tbody></table></div></section>`;}
  const causes={knowledge:'知识内容',routing:'识别与路由',query:'业务查询',workflow:'办理流程',handoff:'协作交接',notification:'通知失败'};
  function qualityView(){return `<div class="notice">按实际根因整改。知识问题需新版发布后用原问题复验；业务查询、交接或通知故障不能靠发布知识直接关闭。</div><section class="panel"><div class="table-wrap"><table><thead><tr><th>原始问题</th><th>根因</th><th>状态</th><th>处理安排</th><th>操作</th></tr></thead><tbody>${state.gaps.map(g=>`<tr><td><strong>${e(g.originalQuery)}</strong><br>${e(g.reason)}</td><td>${e(causes[g.cause])}</td><td>${({open:'待整改',fixing:'待复验',verified:'复验完成'})[g.status]}</td><td>${e(g.plan||'待登记方案')}<br><span class="small muted">${e(g.id)}</span></td><td>${btn('关联事项','case',`data-case="${e(g.caseId)}"`,'small')}${g.status==='open'?btn('登记方案','gap-plan',`data-id="${e(g.id)}"`,'small'):g.status==='fixing'?btn('原问题复验','gap-verify',`data-id="${e(g.id)}"`,'small'):''}</td></tr>`).join('')||'<tr><td colspan="5">从客服工作台或事项详情登记质量问题后，在这里跟进整改。</td></tr>'}</tbody></table></div></section>`;}
  function settingsView(){return `<section class="panel"><div class="panel-head"><h3>接待与跟进设置</h3></div><div class="panel-body">${actor().role==='manager'?`<form id="settings-form"><div class="form-grid">${field('ticketHours','默认后续反馈时限（小时）',state.settings.ticketHours,'number','min="1" max="168" required')}${field('handoffMinutes','转派接收时限（分钟）',state.settings.handoffMinutes,'number','min="1" max="240" required')}</div>${check('accepting','当前接受人工接续',state.settings.accepting)}<div class="form-actions"><button class="primary" type="submit">保存设置</button>${btn('检查转派超时','expire-handoffs')}</div></form>`:'<p>由售后主管维护接待设置，知识运营可查看当前服务情况。</p>'+kv([['人工接续',state.settings.accepting?'接受':'暂不可用'],['默认跟进',state.settings.ticketHours+'小时'],['转派接收时限',state.settings.handoffMinutes+'分钟']])}<h4 class="section-title">在线客服</h4>${state.staff.filter(a=>a.role==='agent').map(a=>`<p>${e(a.name)} ${badge(a.available?'在线':'离线',a.available?'good':'')}</p>`).join('')}</div></section>`;}
  function attachmentPicker(ids=[]){const own=state.attachments.filter(f=>f.customerId==='C001');return `<div class="field full"><label>申请材料</label><input type="file" id="material-file" accept="image/png,image/jpeg,image/webp" aria-label="上传申请材料"><span class="help">选择本地图片，不需要输入内部材料编号。每张不超过500KB，最多选择3张；文件只保存在当前浏览器。</span><div class="attachments">${own.map(f=>`<label class="attachment"><img src="${e(f.dataUrl)}" alt="${e(f.name)}"><span class="file-name"><input type="checkbox" name="attachmentIds" value="${e(f.id)}" ${ids.includes(f.id)?'checked':''}> ${e(f.name)}</span></label>`).join('')}</div></div>`;}
  function openApplication(options={}){options=Object.fromEntries(Object.entries(options).filter(([,v])=>v!==undefined));const c=state.cases.find(c=>c.id===(options.caseId||'')),prefill=c?.prefill||{};ui.form={type:options.type||c?.type||'',orderId:options.orderId||c?.orderId||'',itemId:options.itemId||c?.itemId||'',reason:options.reason||prefill.reason||c?.description||'',attachmentIds:options.attachmentIds||c?.attachmentIds||[],sourceCaseId:c?.id||options.sourceCaseId||'',...prefill,...options};if(!Object.hasOwn(S.TYPES,ui.form.type)||ui.form.type==='logistics')ui.form.type='';applicationForm();}
  function captureApplication(){const form=$('#application-form');if(!form)return;const fd=new FormData(form);ui.form={...ui.form,...Object.fromEntries(fd),attachmentIds:fd.getAll('attachmentIds')};}
  function applicationForm(){const f=ui.form,order=state.orders.find(o=>o.id===f.orderId&&o.customerId==='C001'),items=state.items.filter(i=>i.orderId===order?.id),item=items.find(i=>i.id===f.itemId),product=state.catalog.find(p=>p.id===item?.skuId),p=state.policies.find(p=>p.id===f.type)?.live,needItem=['return_refund','refund_only','exchange','reship','repair'].includes(f.type);let extra='';
    if(f.type==='change_address')extra=field('addressName','收件人',f.addressName??f.address?.name??order?.address.name??'','text','required')+field('addressPhone','联系电话',f.addressPhone??f.address?.phone??order?.address.phone??'','tel','required')+area('addressText','新的完整收货地址',f.addressText??f.address?.text??order?.address.text??'','required maxlength="300"');
    if(f.type==='exchange')extra=select('targetVariant','希望更换的规格',[['','请选择目标规格'],...(product?.variants||[]).map(v=>[v.label,v.label+(v.stock?' · 有货':' · 暂无货')])],f.targetVariant,'required');
    if(f.type==='reship')extra=select('missingScope','缺失范围',[['part','缺少配件'],['whole','缺少整件商品']],f.missingScope||'part')+field('missingName','缺失内容',f.missingName||'','text','required maxlength="100"')+field('missingQuantity','缺失数量',f.missingQuantity||1,'number','min="1" max="10" required');
    if(f.type==='invoice')extra=select('invoiceType','发票抬头类型',[['individual','个人'],['company','企业']],f.invoiceType||'individual')+field('invoiceTitle','发票抬头',f.invoiceTitle||'','text','required')+field('taxId','纳税人识别号（企业必填）',f.taxId||'','text','maxlength="20"')+field('email','接收邮箱',f.email||'','email','required');
    if(f.type==='price_protection')extra=area('comparison','对比活动、商品规格与价格依据',f.comparison||'','required maxlength="500"');
    const hint=f.type==='cancel_order'?'取消与退款分别跟踪。已出库或锁定的订单需人工核实，不能承诺拦截。':f.type==='change_address'?'提交前重新核对仓储状态，只有仍未出库且未锁定才能变更。':['exchange','reship'].includes(f.type)?'审核通过后按申请类型安排寄回或履约协调，不自动退款，不将受理显示为已寄出。':['invoice','price_protection','repair'].includes(f.type)?'先收集必要信息并交责任组核实；实际开票、补差和维修结果需后续履约回执。':'申请提交后需按规则审核；退款金额和是否寄回以批准的业务记录为准。';
    modal('核对服务申请',`<form id="application-form"><div class="notice">${hint}</div><div class="form-grid">${select('type','办理类型',[['','请选择处理方式'],...Object.entries(S.TYPES).filter(([k])=>k!=='logistics')],f.type,'required')}${select('orderId','本人订单',[['','请选择订单'],...myOrders().map(o=>[o.id,o.id+' · '+orderLabel(o.status)])],f.orderId,'required')}${needItem?select('itemId','本次办理的商品',[['','请选择商品'],...items.map(i=>[i.id,i.name+' · '+i.variant])],f.itemId,'required')+field('quantity','商品数量',1,'number','readonly'):''}${extra}<div class="full">${area('reason','申请原因 / 问题说明',f.reason,'required maxlength="2000"')}</div>${!['cancel_order','change_address'].includes(f.type)?attachmentPicker(f.attachmentIds):''}</div><p class="small muted">${e(p?.source||'商家规则')} · v${p?.version||1}；${p?.materialRequired?'本类型需要申请材料。':'必要时可在原申请补充。'} 预览不代表受理，只有本人确认后提交。</p><div class="form-actions"><button type="submit" class="primary">核对申请预览</button>${btn('取消填写','close')}</div></form>`,'application');}
  function showPreview(d){const v=d.data,item=state.items.find(i=>i.id===v.itemId),order=state.orders.find(o=>o.id===v.orderId);ui.form.draftId=d.id;modal('确认申请内容',`<div class="notice">请核对本次申请。返回修改或取消不会创建正式申请；最终提交时再次核对订单及规则。</div>${kv([['服务类型',S.TYPES[v.type]],['订单',v.orderId],['商品',item?item.name+' · '+item.variant:undefined],['数量',v.quantity],['原因',v.reason],['希望更换',v.targetVariant],['缺失内容',v.missingName?`${v.missingName} × ${v.missingQuantity}`:undefined],['新收货信息',v.address?[v.address.name,v.address.phone,v.address.text].join(' · '):undefined],['发票抬头',v.invoiceTitle],['纳税人识别号',v.taxId],['接收邮箱',v.email],['价格对比',v.comparison],['退款金额来源',['return_refund','refund_only'].includes(v.type)?'订单明细实付 '+M.amount(item.paidCents)+'，仍需审核':v.type==='cancel_order'?'若已付款，取消后按原支付金额独立处理退款':undefined],['责任组',groups[d.policy.team]],['下次反馈','受理后'+d.policy.feedbackHours+'小时内'],['规则快照',d.policy.source+' v'+d.policy.version]])}${evidence(v.attachmentIds)}<div class="form-actions">${btn('确认提交','confirm-application',`data-draft="${e(d.id)}"`,'primary')}${btn('返回修改','edit-application')}${btn('取消本次申请','discard-application',`data-draft="${e(d.id)}"`)}</div>`,'preview');}
  function supplementModal(caseId){const c=state.cases.find(c=>c.id===caseId),r=application(c);ui.form={caseId,applicationId:r.id,reason:'',attachmentIds:[]};showSupplement();}
  function showSupplement(){const f=ui.form;modal('在原申请补充资料',`<form id="supplement-form"><input type="hidden" name="applicationId" value="${e(f.applicationId)}">${area('reason','补充说明',f.reason,'required')}${attachmentPicker(f.attachmentIds)}<div class="form-actions"><button type="submit" class="primary">提交至原申请</button>${btn('取消','close')}</div></form>`,'supplement');}
  function couponModal(orderId=''){modal('核对优惠资格',`<form id="coupon-form">${select('orderId','本人订单',[['','请选择订单'],...myOrders().map(o=>[o.id,o.id])],orderId,'required')}${select('couponId','查询优惠券',state.coupons.map(c=>[c.id,c.name]))}<div class="notice">查询商品范围、门槛、有效期和叠加限制；不会自动改变订单或补差价。</div><div class="form-actions"><button type="submit" class="primary">查询资格</button></div></form>`,'coupon');}
  function checks(validation){return validation?`<div class="checks">${validation.checks.map(c=>`<div>${badge(c.passed?'通过':'未通过',c.passed?'good':'bad')} ${e(c.name)}</div>`).join('')}</div>`:'';}
  function policyModal(type){const p=state.policies.find(p=>p.id===type),v=p.draft||p.live;modal(v.title+' · 场景配置',`<form id="policy-form"><input type="hidden" name="type" value="${e(type)}"><div class="row">${check('enabled','接受新申请',v.enabled)}${check('materialRequired','申请需提供材料',v.materialRequired)}${check('requiresReturn','审核后需寄回验收',v.requiresReturn)}</div><div class="form-grid">${select('team','业务责任组',Object.entries(groups),v.team)}${field('feedbackHours','受理后反馈时限（小时）',v.feedbackHours,'number','required min="1" max="168"')}${field('source','规则依据',v.source,'text','required')}${field('effectiveAt','生效日期',v.effectiveAt,'date','required')}${field('expiresAt','失效日期（可选）',v.expiresAt,'date')}${field('feeBearer','运费承担说明',v.feeBearer,'text','required')}${field('returnContact','退回收件人',v.returnContact)}${field('returnPhone','收件电话',v.returnPhone)}<div class="full">${field('returnAddress','寄回地址',v.returnAddress)}${area('returnInstructions','寄回指引',v.returnInstructions)}</div></div>${checks(p.validation)}<div class="form-actions"><button type="submit" class="primary">保存草稿</button>${p.draft?btn('校验草稿','test-policy',`data-type="${e(type)}"`)+btn('发布当前草稿','publish-policy',`data-type="${e(type)}"`):''}${btn('关闭','close')}</div><p class="help">修改仅写入草稿；校验并发布后新申请使用新版，既有申请不被追溯修改。</p></form>`,'policy');}
  function knowledgeModal(id=''){const k=state.knowledge.find(k=>k.id===id),v=k?.draft||k?.live||{title:'',question:'',keywords:[],answer:'',source:'',effectiveAt:new Date().toISOString().slice(0,10),expiresAt:'',positive:'',negative:''};modal(k?'编辑知识与验证':'新增知识',`<form id="knowledge-form"><input type="hidden" name="id" value="${e(id)}"><div class="form-grid">${field('title','知识标题',v.title,'text','required')}${field('question','标准问题',v.question,'text','required')}<div class="full">${field('keywords','匹配关键词（逗号分隔）',v.keywords.join('，'),'text','required')}${area('answer','正式答复',v.answer,'required maxlength="4000"')}</div>${field('source','依据来源',v.source,'text','required')}${field('effectiveAt','生效日期',v.effectiveAt,'date','required')}${field('expiresAt','失效日期（可选）',v.expiresAt,'date')}${field('positive','正例问法',v.positive,'text','required')}${field('negative','反例问法',v.negative,'text','required')}</div>${checks(k?.validation)}<div class="form-actions"><button type="submit" class="primary">保存草稿</button>${k?.draft?btn('运行正反例','test-knowledge',`data-id="${e(id)}"`)+btn('发布知识','publish-knowledge',`data-id="${e(id)}"`):''}${k?.live&&!k.disabled?btn('停用当前知识','disable-knowledge',`data-id="${e(id)}"`):''}</div></form>`,'knowledge');}
  function simpleForm(title,command,base,fields){modal(title,`<form id="command-form"><input name="command" type="hidden" value="${e(command)}"><input name="base" type="hidden" value="${e(JSON.stringify(base))}">${fields}<div class="form-actions"><button type="submit" class="primary">确认提交</button>${btn('取消','close')}</div></form>`,'command');}
  function commandModal(command,caseId,extra={}){const c=state.cases.find(c=>c.id===caseId),r=c&&application(c),f=c&&refund(c),h=state.handoffs.find(h=>h.caseId===caseId&&h.status==='pending');const base={caseId,applicationId:r?.id,refundId:f?.id,conversationId:c?.conversationIds.at(-1),handoffId:h?.id,...extra};
    const reason=(label='处理依据 / 说明')=>area('reason',label,'','required maxlength="2000"');const later=(label='下一次反馈时间')=>field('nextAt',label,isoLocal(Date.now()+86400000),'datetime-local','required');
    const schemas={claim:['确认接管事项','<div class="notice">接管后会话进入人工接待；机器人不再自动公开回复。已有信息将一并保留。</div>'],approve:['审核通过',reason('审批依据与处理方案')],reject:['审核不通过',reason('不通过依据与可复核说明')],requestSupplement:['请求补充资料',reason('需要补充什么，以及原因')],requestReview:['申请复核',reason('复核理由与补充说明')],requestWithdrawal:['申请撤回',reason('撤回原因')],denyWithdrawal:['核实撤回请求',reason('不予直接撤回的依据与后续安排')],submitReturn:['登记寄回运单',field('carrier','承运商','','text','required')+field('tracking','寄回运单号','','text','required')],receiveReturn:['登记仓库收货',reason('收货核对依据')],inspect:['登记验收结果',select('outcome','验收结论',[['pass','验收通过'],['exception','验收存在差异，转复核']])+reason('验收依据')],resolveInspection:['完成验收复核',select('outcome','复核结论',[['pass','复核通过，恢复办理'],['exception','仍有差异，继续核实'],['reject','复核不通过，反馈依据']])+reason('复核证据与结论')],submitRefund:['提交原退款请求',kv([['核定金额',f?M.amount(f.amountCents):''],['原请求号',f?.requestId||'首次提交时生成']])+'<div class="notice">按原批准结果提交；重复点击不会创建第二笔独立退款。</div>'],queryRefund:['查询原退款结果',kv([['原请求号',f?.requestId]])],recordRefundReceipt:['登记渠道回执',kv([['原请求号',f?.requestId],['核定金额',f?M.amount(f.amountCents):'']])+select('outcome','渠道状态',[['unknown','结果未知，继续核实'],['processing','仍在处理中'],['success','渠道返回成功'],['failed','渠道执行失败']])+field('receiptId','渠道回执号','','text','required')+field('version','回执版本',(f?.receiptVersion||0)+1,'number','required min="1"')+reason('渠道核实记录与说明')],note:['添加内部备注',area('body','内部备注（客户不可见）','','required')],followup:['安排后续反馈',later()+reason('具体跟进事项')],scheduleCallback:['安排回访',later('回访时间')+reason('回访目的')],callbackResult:['记录回访结果',select('outcome','是否联系到客户',[['reached','已联系到'],['not_reached','未联系到']])+reason('回访记录')+later('未联系到时的下次反馈时间')],handoff:['转派接续客服',select('targetId','接续客服',state.staff.filter(a=>a.role==='agent'&&a.id!==c?.ownerId).map(a=>[a.id,a.name]))+reason('已处理内容、未完事项与接续要求')],acceptHandoff:['确认接收转派','<div class="notice">接收后由当前客服接续该会话及原客服名下未完事项，业务责任组不变；原材料与首次受理时间保持不变。</div>'],rejectHandoff:['拒收转派',reason('拒收原因，原责任人继续跟进')],resolveLogistics:['物流核实结论',select('outcome','核实结果',[['in_transit_explained','运输正常，已核实并说明'],['delivered','已核实实际送达'],['needs_action','仍需补发或售后处理']])+reason('核实证据与说明')],resolvePayment:['支付核实结果',select('outcome','核实状态',[['unknown','仍未知'],['paid','已支付'],['unpaid','确认未支付'],['pending','支付处理中'],['not_found','未查到原记录'],['failed','查询失败']])+field('amountCents','已支付时的金额（分）',c?state.items.filter(i=>i.orderId===c.orderId).reduce((n,i)=>n+i.paidCents,0):0,'number','min="0"')+reason('支付服务核实依据')],resolveDispute:['完成原事项异议复核',reason('复核依据、业务结果与反馈安排')],completeInquiry:['登记咨询处理结论',reason('实际完成依据与对外结论')],closeConversation:['结束本次接待','<div class="notice">仅结束会话。未办结事项继续保留责任组和下次反馈安排，不将售后或退款自动办结。</div>'],flagCase:['登记质量问题',select('cause','根因类型',Object.entries(causes))+area('originalQuery','原始用户问题',c?.description||c?.title||'','required')+reason('问题说明')],notificationResult:['核实通知状态',select('status','通知状态',[['unknown','送达未知，查原发送记录'],['failed','明确发送失败，安排补救'],['delivered','已有送达回执']])+reason('通知依据与后续安排')]};
    if(command==='recordRefundReceipt'){base.requestId=f?.requestId;base.amountCents=f?.amountCents;}if(!schemas[command])throw Error('暂不支持该操作');simpleForm(schemas[command][0],command,base,schemas[command][1]);}
  document.addEventListener('click',async event=>{const target=event.target.closest('button');if(!target)return;try{
    if(target.dataset.view){close();ui.view=target.dataset.view;render();return;}
    if(target.dataset.page){ui.page=target.dataset.page;render();return;}
    if(target.dataset.opsPage){ui.opsPage=target.dataset.opsPage;render();return;}
    const d=target.dataset,act=d.action;if(!act)return;
    if(act==='close'){close();return;}
    if(act==='goto-orders'||act==='goto-progress'){close();ui.page=act==='goto-orders'?'orders':'progress';render();return;}
    if(act==='select-case'){ui.caseId=d.case;if(ui.modal==='queue')close();render();return;}
    if(act==='desk-queue'){if(ui.view==='desk')openDeskQueue();return;}
    if(act==='case'){caseModal(d.case);return;}
    if(act==='desk-context'){const c=state.cases.find(c=>c.id===d.case);if(!c||ui.view!=='desk')return;modal('关联信息与业务事件',deskContext(c,null),'case');return;}
    if(act==='sop-send'||act==='sop-fill'){const p=P.build(state,d.case,{agentId:actor().id,fmt:t})?.prefill,body=p?.options[Number(d.alt)];if(!p||p.node!==d.node||!body)throw Error('SOP 节点已变化，请核对后重新操作');
      if(act==='sop-fill'){ui.replyDraft={caseId:d.case,body,sopNode:p.node};render();const box=$('#reply-form [name=body]');box?.focus?.();box?.setSelectionRange?.(body.length,body.length);return;}
      run('reply',{caseId:d.case,body,sopNode:p.node});ui.replyDraft=null;ui.sopAlt=null;render();toast('已发送「'+p.label+'」话术');return;}
    if(act==='sop-alt'){keepReplyDraft(d.case);ui.sopAlt={caseId:d.case,node:d.node,index:Number(d.alt)+1};render();return;}
    if(act==='desk-workflow'){const c=state.cases.find(c=>c.id===d.case);if(!c||ui.view!=='desk')return;modal('服务处理',deskWorkflow(c,null),'workflow');return;}
    if(act==='application'){openApplication({type:d.kind||undefined,orderId:d.order||undefined,itemId:d.item||undefined,caseId:d.case||undefined});return;}
    if(act==='other-services'){modal('选择服务',`<p class="muted">先核实申请信息，再交对应业务责任组办理。</p><div class="actions">${['invoice','price_protection','repair'].map(type=>btn(S.TYPES[type],'application',`data-kind="${type}" data-order="${e(d.order)}"`,'primary')).join('')}</div>`,'services');return;}
    if(act==='message-action'){if(['orders','products','progress'].includes(d.kind)){ui.page=d.kind;render();return;}if(d.kind==='coupon'){couponModal(d.order);return;}openApplication({type:d.kind==='aftersales'?undefined:d.kind,orderId:d.order||undefined,itemId:d.item||undefined,caseId:d.case||undefined});return;}
    if(act==='coupon'){couponModal(d.order||'');return;}
    if(act==='human'){const cv=ensureOpen();run('requestHuman',{conversationId:cv.id});ui.page='chat';render();toast('已保留诉求和人工接续安排');return;}
    if(act==='new-chat'){ui.conversationId=run('newConversation',{});ui.page='chat';render();return;}
    if(act==='history'){const rows=state.conversations.filter(v=>v.customerId==='C001');modal('历史咨询',rows.map(v=>`<div class="preview-block"><div class="row between"><span>${e(t(v.createdAt))}</span>${badge(v.status==='open'?'可继续':'已结束')}</div><p>${e(v.messages.find(m=>m.role==='customer')?.body||'尚未发送问题')}</p>${btn('查看咨询','open-conversation',`data-id="${e(v.id)}"`)}</div>`).join(''),'history');return;}
    if(act==='open-conversation'){ui.conversationId=d.id;ui.page='chat';close();render();return;}
    if(act==='context'){const cv=ensureOpen();run('setContext',{conversationId:cv.id,orderId:d.order,itemId:d.item});ui.page='chat';render();toast('已选定本次咨询商品');$('#chat-input').focus();return;}
    if(act==='query-logistics'){const cv=ensureOpen();const cid=run('queryLogistics',{conversationId:cv.id,orderId:d.order,itemId:d.item});ui.page='chat';render();toast('已查询对应包裹');return;}
    if(act==='query-order'){const cv=ensureOpen();run('queryOrder',{conversationId:cv.id,orderId:d.order});ui.page='chat';render();return;}
    if(act==='ask-product'){const cv=ensureOpen();run('say',{conversationId:cv.id,body:d.text});ui.page='chat';render();return;}
    if(act==='confirm-application'){target.disabled=true;try{const value=run('confirm',{draftId:d.draft});close();ui.page='progress';render();toast(value.duplicate?'本申请已提交，继续原办理记录':'申请已提交，查看进度与下一步');if(value.caseId)caseModal(value.caseId);}finally{target.disabled=false;}return;}
    if(act==='edit-application'){applicationForm();return;}
    if(act==='discard-application'){run('discardDraft',{draftId:d.draft});close();render();toast('已取消草稿，未创建正式申请');return;}
    if(act==='supplement'){supplementModal(d.case);return;}
    if(act==='feedback'){simpleForm('反馈处理结果','feedback',{caseId:d.case},select('resolved','问题是否解决',[['true','已解决'],['false','未解决，需要继续核实']])+select('satisfaction','满意度（可不评价）',[['','暂不评价'],['5','5 · 很满意'],['4','4 · 满意'],['3','3 · 一般'],['2','2 · 不满意'],['1','1 · 很不满意']])+area('reason','补充说明'));return;}
    if(act==='command'){commandModal(d.command,d.case,{...(d.callback?{callbackId:d.callback}:{}),...(d.notification?{id:d.notification}:{})});return;}
    if(act==='prefill'){const c=state.cases.find(c=>c.id===d.case);simpleForm('协助整理申请','prepareDraft',{caseId:c.id},select('type','申请类型',Object.entries(S.TYPES).filter(([k])=>!['logistics'].includes(k)),Object.hasOwn(S.TYPES,c.type)?c.type:'return_refund')+area('reason','根据已提供信息整理原因',c.description||'','required')+field('targetVariant','换货目标规格（换货时填写）',c.prefill?.targetVariant||'')+field('missingName','缺失内容（补发时填写）',c.prefill?.missingName||'')+'<p class="help">这里只整理资料。客户需打开原事项核对并确认，客服不能代替提交。</p>');return;}
    if(act==='presence'){run('presence',{available:!state.staff.find(a=>a.id===actor().id).available});render();return;}
    if(act==='expire-handoffs'){const n=run('expireHandoffs',{});render();toast('已核对 '+n+' 项超时转派，原责任未丢失');return;}
    if(act==='policy'){policyModal(d.type);return;}
    if(act==='test-policy'){run('testPolicy',{type:d.type});policyModal(d.type);render();return;}
    if(act==='publish-policy'){run('publishPolicy',{type:d.type});policyModal(d.type);render();toast('新版场景配置已生效');return;}
    if(act==='knowledge'){knowledgeModal(d.id||'');return;}
    if(act==='test-knowledge'){run('testKnowledge',{id:d.id});knowledgeModal(d.id);render();return;}
    if(act==='publish-knowledge'){run('publishKnowledge',{id:d.id});knowledgeModal(d.id);render();toast('知识已发布，正式问答使用新版');return;}
    if(act==='disable-knowledge'){simpleForm('停用知识','disableKnowledge',{id:d.id},area('reason','停用原因','','required'));return;}
    if(act==='gap-plan'){const g=state.gaps.find(g=>g.id===d.id);simpleForm('登记整改方案','planGap',{id:g.id},area('plan','实际修改对象与验证方式','','required')+(g.cause==='knowledge'?select('knowledgeId','关联知识',state.knowledge.map(k=>[k.id,(k.live||k.draft).title])):select('ownerId','整改责任人',state.staff.map(a=>[a.id,a.name]))));return;}
    if(act==='gap-verify'){const g=state.gaps.find(g=>g.id===d.id);simpleForm('用原问题复验','verifyGap',{id:g.id},`<div class="notice">原问题：${e(g.originalQuery)}</div>${area('evidence','实际复验过程与结果','','required')}${g.cause!=='knowledge'?field('recordId','业务修复验证记录号','','text','required'):''}`);return;}
  }catch(err){showError(err);}});
  document.addEventListener('submit',event=>{const form=event.target,formId=form.getAttribute('id');if(!formId)return;event.preventDefault();try{const fd=new FormData(form),v=Object.fromEntries(fd);switch(formId){
    case 'chat-form':{const cv=ensureOpen();run('say',{conversationId:cv.id,body:v.body});render();$('#chat-input')?.focus();break;}
    case 'reply-form':run('reply',v);ui.replyDraft=null;ui.sopAlt=null;render();toast('已由客服确认发送');break;
    case 'application-form':{captureApplication();const f=ui.form,cv=ensureOpen();const v={...f,address:{name:f.addressName,phone:f.addressPhone,text:f.addressText},conversationId:cv.id};const preview=run('preview',v);showPreview(preview);break;}
    case 'supplement-form':{run('supplement',{...v,attachmentIds:fd.getAll('attachmentIds')});close();render();caseModal(ui.form.caseId);toast('材料已补充到原申请');break;}
    case 'coupon-form':{const cv=ensureOpen(),r=run('queryCoupon',{...v,conversationId:cv.id});modal('优惠资格结果',`${badge(r.eligible?'当前条件符合':'当前不适用',r.eligible?'good':'warn')}<p>${e(r.reason)}</p>${kv([['订单',r.orderId],['依据来源',r.source],['查询时间',t(r.queriedAt)]])}<div class="notice">资格查询不会自动改价或退差价。</div><div class="actions">${btn('完成','close')}</div>`,'coupon-result');render();break;}
    case 'policy-form':{const data={...v,enabled:fd.has('enabled'),requiresReturn:fd.has('requiresReturn'),materialRequired:fd.has('materialRequired')};run('savePolicy',data);policyModal(v.type);render();toast('草稿已保存，尚未生效');break;}
    case 'knowledge-form':{const id=run('saveKnowledge',v);knowledgeModal(id);render();toast('知识草稿已保存');break;}
    case 'settings-form':run('serviceSettings',{...v,accepting:fd.has('accepting')});render();toast('接待设置已保存');break;
    case 'command-form':{const base=JSON.parse(v.base),command=v.command;delete v.base;delete v.command;const data={...base,...v};if('nextAt' in data)data.nextAt=new Date(data.nextAt).getTime();if('resolved'in data)data.resolved=data.resolved==='true';if(data.satisfaction==='')delete data.satisfaction;const result=run(command,data);close();render();if(command==='queryRefund'){modal('原退款查询结果',kv([['退款记录',result.id],['原请求号',result.requestId],['当前结果',({processing:'处理中',unknown:'结果未知，继续核实',success:'渠道成功',failed:'执行失败'})[result.status]],['金额',M.amount(result.amountCents)],['查询时间',t(result.queriedAt)]])+'<p class="muted">查询未创建新的退款请求。</p>','refund-result');}else {toast('已记录本次处理结果');if(ui.view==='customer'&&base.caseId)caseModal(base.caseId);}break;}
  }}catch(err){showError(err);}});
  document.addEventListener('change',async event=>{try{const el=event.target;
    if(el.name==='deskActor'){ui.deskActor=el.value;render();return;}if(el.name==='opsActor'){ui.opsActor=el.value;render();return;}if(el.name==='queueFilter'||el.name==='queueDialogFilter'){ui.queueFilter=el.value;render();if(el.name==='queueDialogFilter')openDeskQueue();return;}
    if(el.closest('#application-form')&&['type','orderId','itemId'].includes(el.name)){captureApplication();if(el.name==='orderId'){ui.form.itemId='';for(const k of ['targetVariant','addressName','addressPhone','addressText'])delete ui.form[k];ui.form.sourceCaseId='';}if(el.name==='itemId')delete ui.form.targetVariant;if(el.name==='type')for(const k of ['targetVariant','missingName','invoiceTitle','taxId','comparison'])delete ui.form[k];applicationForm();return;}
    if(el.id==='material-file'&&el.files?.length){if(ui.modal==='application')captureApplication();else if(ui.modal==='supplement'){const fd=new FormData($('#supplement-form'));ui.form.reason=fd.get('reason');ui.form.attachmentIds=fd.getAll('attachmentIds');}const file=el.files[0];if(file.size>512000)throw Error('单张图片不能超过500KB，请选择较小的照片');if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('仅支持PNG、JPEG和WebP图片');const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('材料读取失败'));reader.readAsDataURL(file);});const id=run('addAttachment',{name:file.name,mime:file.type,size:file.size,dataUrl});ui.form.attachmentIds=[...(ui.form.attachmentIds||[]),id].slice(-3);if(ui.modal==='application')applicationForm();else showSupplement();toast('图片已添加，请核对后提交');}
  }catch(err){showError(err);}});
  document.addEventListener('keydown',event=>{if(event.target.id==='chat-input'&&event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();$('#chat-form').requestSubmit();}});
  $('#dialog-close').addEventListener('click',close);
  dialog.addEventListener('cancel',()=>{ui.modal='';});
  // Read the current value: queued storage events may describe an older write.
  window.addEventListener('storage',event=>{if(event.key!==KEY||!state||!storageAvailable)return;try{const raw=localStorage.getItem(KEY);if(raw===original)return;const fresh=JSON.parse(raw);S.validateState(fresh);if(fresh.revision<=state.revision)throw new Error('记录版本变化');state=fresh;original=raw;if(dialog.open){close();toast('同一浏览器的记录已变化，请重新打开并核对后提交');}render();}catch(err){toast('另一窗口的记录无法读取，请刷新后检查；当前内容未覆盖');}});
  if(storageAvailable){
    editingAllowed=false;
    if(typeof navigator!=='undefined'&&navigator.locks?.request)navigator.locks.request(KEY,{mode:'exclusive',ifAvailable:true},lock=>{
      if(!lock){render();return;}
      editingAllowed=true;render();
      return new Promise(()=>{}); // Hold the edit lock until the document unloads.
    }).catch(()=>{editingAllowed=false;render();toast('无法取得编辑权限，请关闭其他页面后刷新重试。');});
    else editingNotice='本页仅供查看。当前浏览器不支持安全编辑，请使用现代浏览器通过本地 HTTP 地址打开。';
  }
  render();
})();
